import {githubMode} from '../../../lib/self-host-config';
import {githubAPI} from '../../../lib/github-api';
import {confirmedLocation,validDate} from '../../../lib/photo-metadata';
import {getChatGPTUser} from '../../chatgpt-auth';
import {database,privateHeaders} from '../../../lib/storage';
export const dynamic='force-dynamic';
const json=(v:unknown,status=200)=>Response.json(v,{status,headers:privateHeaders});
export async function GET(){if(githubMode())return githubAPI(undefined,'list');const u=await getChatGPTUser();if(!u)return json({error:'请先登录'},401);try{const db=database();const [c,s,p]=await Promise.all([db.prepare('SELECT * FROM checkins WHERE owner=? ORDER BY date DESC, created DESC').bind(u.userId).all(),db.prepare('SELECT * FROM statuses WHERE owner=?').bind(u.userId).all(),db.prepare('SELECT id,checkin FROM photos WHERE owner=? AND checkin IS NOT NULL').bind(u.userId).all()]);const drafts=await db.prepare('SELECT id FROM photos WHERE owner=? AND checkin IS NULL ORDER BY created').bind(u.userId).all();return json({checkins:c.results,statuses:s.results,photos:p.results,drafts:drafts.results});}catch(e){console.error(e);return json({error:'暂时无法读取，请重试'},503);}}
export async function POST(req:Request){if(githubMode())return githubAPI(req,'save');const u=await getChatGPTUser();if(!u)return json({error:'请先登录'},401);if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return json({error:'无效请求来源'},403);try{if(Number(req.headers.get('content-length'))>20000)return json({error:'内容过长'},413);const b=await req.json() as Record<string,any>;const str=(k:string,max:number)=>typeof b[k]==='string'&&b[k].trim().length<=max?b[k].trim():'';const id=str('id',60),prefecture=str('prefecture',50),city=str('city',100),place=str('place',150),placeKey=str('placeKey',250),date=str('date',10),note=str('note',1000);const depths=[b.depth,b.prefDepth,b.cityDepth];if(!/^[a-zA-Z0-9-]{10,60}$/.test(id)||!prefecture||!place||!placeKey||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!depths.every(x=>Number.isInteger(x)&&x>=0&&x<=5)||!['restaurant','place'].includes(b.kind)||typeof b.eaten!=='boolean'||!Array.isArray(b.photos)||b.photos.length>6||!validDate(date))return json({error:'请检查地点、日期与打卡内容'},400);
let location;try{location=confirmedLocation(b.location);}catch{return json({error:'请确认有效地图坐标'},400);}
const db=database();const exists=await db.prepare('SELECT id FROM checkins WHERE id=? AND owner=?').bind(id,u.userId).first();if(exists)return json({id,saved:true});
for(const p of b.photos){if(typeof p!=='string')return json({error:'照片无效'},400);const row=await db.prepare('SELECT id FROM photos WHERE id=? AND owner=? AND checkin IS NULL').bind(p,u.userId).first();if(!row)return json({error:'照片不存在或已使用'},400);}
const statements=[db.prepare('INSERT INTO checkins (id,owner,prefecture,city,place,place_key,kind,date,note,depth,eaten,created,latitude,longitude,location_source) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,u.userId,prefecture,city,place,placeKey,b.kind,date,note,b.depth,b.eaten?1:0,new Date().toISOString(),location?.latitude??null,location?.longitude??null,location?.source??null)];
for(const [scope,label,depth,eaten] of [['prefecture',prefecture,b.prefDepth,0],...(city?[['city',prefecture+' / '+city,b.cityDepth,0]]:[]),['place',placeKey,b.depth,b.eaten?1:0]] as [string,string,number,number][]){statements.push(db.prepare('INSERT INTO statuses (id,owner,scope,label,depth,eaten) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET depth=excluded.depth,eaten=excluded.eaten').bind(JSON.stringify([u.userId,scope,label]),u.userId,scope,label,depth,eaten));}
for(const p of b.photos)statements.push(db.prepare('UPDATE photos SET checkin=? WHERE id=? AND owner=? AND checkin IS NULL').bind(id,p,u.userId));await db.batch(statements);return json({id,saved:true},201);
}catch(e){console.error(e);return json({error:'保存未完成，请保留内容后重试'},503);}}
