import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyJournal,journalSchema,photoProposalSchema,sharedJournal,setMarkers} from '../lib/travel-data.ts';
import {blankPhotoDetails,photoEditInput,savePhotoDetails} from '../lib/photo-records.ts';
import {buildPoster,posterStyles,posterFormats} from '../lib/travel-poster.ts';
import type {MapFeature} from '../lib/geography.ts';
const owner='synthetic-owner';
function fixture(){const j=emptyJournal(owner);for(const id of ['synthetic-photo-01','synthetic-photo-02'])j.photos.push({id,owner,sha:'a'.repeat(40),digest:'fixture',checkin:null,created:'2026-01-01'});return j}
const complete={...blankPhotoDetails,country:'JP',prefecture:'架空県',city:'架空市',place:'合成地点',date:'2026-01-02'};
test('uploaded photo supports partial private information without creating a visit; proposals restore after parsing',()=>{const j=fixture();j.photos[0].proposal={date:'2026-01-02',gps:{latitude:0,longitude:0}};savePhotoDetails(j,owner,j.photos[0].id,{details:{...blankPhotoDetails,note:'仅记笔记'},confirmed:false});const restored=journalSchema.parse(JSON.parse(JSON.stringify(j)));assert.equal(restored.photos[0].details?.note,'仅记笔记');assert.deepEqual(restored.photos[0].proposal,j.photos[0].proposal);assert.equal(j.checkins.length,0);assert.equal(sharedJournal(j).photos.length,0)});
test('each confirmed photo produces its own visit, retries and edits never duplicate visits or reset history',()=>{const j=fixture();setMarkers(j,owner,[{scope:'prefecture',label:'架空県',depth:4,eaten:false}]);for(const p of j.photos)savePhotoDetails(j,owner,p.id,{details:complete,confirmed:true});assert.equal(j.checkins.length,2);savePhotoDetails(j,owner,j.photos[0].id,{details:{...complete,note:'新笔记'},confirmed:true});assert.equal(j.checkins.length,2);assert.equal(j.checkins[0].note,'新笔记');assert.equal(savePhotoDetails(j,owner,j.photos[0].id,{details:{...complete,note:'新笔记'},confirmed:true}),false);assert.equal(j.statuses[0].depth,4);assert.equal(j.checkins[0].latitude,null)});
test('confirmation validates missing date/region, malformed GPS and owner; removed items cannot be edited',()=>{const j=fixture();assert.throws(()=>savePhotoDetails(j,'other',j.photos[0].id,{details:complete,confirmed:true}));assert.throws(()=>savePhotoDetails(j,owner,j.photos[0].id,{details:blankPhotoDetails,confirmed:true}));assert.throws(()=>photoEditInput.parse({details:{...complete,date:'2026-02-30'},confirmed:false}));assert.throws(()=>photoProposalSchema.parse({gps:{latitude:91,longitude:0}}));assert.throws(()=>savePhotoDetails(j,owner,j.photos[0].id,{details:{...complete,latitude:35,longitude:null},confirmed:true}));j.photos[0].removed=true;assert.throws(()=>savePhotoDetails(j,owner,j.photos[0].id,{details:complete,confirmed:true}));assert.equal(j.checkins.length,0)});
test('changing an existing location requires re-confirmation and revokes publishing',()=>{const j=fixture();savePhotoDetails(j,owner,j.photos[0].id,{details:complete,confirmed:true});j.checkins[0].published=true;assert.throws(()=>savePhotoDetails(j,owner,j.photos[0].id,{details:{...complete,place:'另一合成地点'},confirmed:false}));assert.equal(j.checkins[0].place,complete.place);savePhotoDetails(j,owner,j.photos[0].id,{details:{...complete,note:'私有新增笔记'},confirmed:false});assert.equal(j.checkins[0].published,false)});
test('editing one photo of a legacy album keeps other photos and original record intact',()=>{const j=fixture();savePhotoDetails(j,owner,j.photos[0].id,{details:complete,confirmed:true});j.photos[1].checkin=j.photos[0].checkin;savePhotoDetails(j,owner,j.photos[1].id,{details:{...complete,date:'2026-01-03'},confirmed:true});assert.equal(j.checkins.length,2);assert.notEqual(j.photos[0].checkin,j.photos[1].checkin);assert.equal(j.checkins[0].date,'2026-01-02');savePhotoDetails(j,owner,j.photos[1].id,{details:{...complete,date:'2026-01-03'},confirmed:true});assert.equal(j.checkins.length,2)});
test('all three styles support every format, safely escape copy and never export proposal coordinates or private notes',()=>{const features:MapFeature[]=[{properties:{id:1,name:'合成区域'},geometry:{type:'MultiPolygon',coordinates:[[[[0,0],[1,0],[1,1],[0,0]]]]}}];for(const style of Object.keys(posterStyles) as (keyof typeof posterStyles)[])for(const format of Object.keys(posterFormats) as (keyof typeof posterFormats)[]){const svg=buildPoster({scope:'sichuan',features,visits:[],title:'<script>',subtitle:'&题记',style,format,mapScale:100});assert.ok(!svg.includes('<script>'));assert.ok(svg.includes('&amp;题记'));assert.ok(svg.includes(posterFormats[format].width.toString()));assert.ok(svg.includes(`Style: ${style}`));assert.ok(!svg.includes('NaN'));}});

test('date diagnostics remain private and old proposals remain compatible',()=>{assert.deepEqual(photoProposalSchema.parse({date:'2026-01-02'}),{date:'2026-01-02'});assert.throws(()=>photoProposalSchema.parse({dateSource:'original'}));assert.throws(()=>photoProposalSchema.parse({dateStatus:'read'}));assert.throws(()=>photoProposalSchema.parse({date:'2026-01-02',dateStatus:'missing'}));for(const dateStatus of ['missing','invalid','error'] as const)assert.equal(photoProposalSchema.parse({dateStatus}).dateStatus,dateStatus)});
