'use client';
import PuzzleLayer,{type PuzzleLayerProps} from './puzzle-layer';
import SelectField from './select-field';
import {useRef,useState,useEffect} from 'react';
import {Plus,Minus,LocateFixed,MapPin} from 'lucide-react';
export type AtlasFeature={properties:{id:number,name:string},geometry:{coordinates:number[][][][]}};
type Props=PuzzleLayerProps&{features:AtlasFeature[];pref:string;depth:number;recorded:Set<string>;onSelect:(pref:string)=>void;visits?:{id:string;latitude:number;longitude:number;label:string;prefecture:string}[];onVisit?:(id:string)=>void};
const project=([x,y]:number[])=>[(x-122)*23,(46-y)*23];
function path(f:AtlasFeature,inset=false){return f.geometry.coordinates.filter(poly=>inset||poly[0].some(p=>p[1]>29)).map(poly=>poly.map(ring=>'M'+ring.map(p=>project(p).join(',')).join('L')+'Z').join(' ')).join(' ');}
function center(f:AtlasFeature){const p=f.geometry.coordinates[0][0].map(project);return [(Math.min(...p.map(v=>v[0]))+Math.max(...p.map(v=>v[0])))/2,(Math.min(...p.map(v=>v[1]))+Math.max(...p.map(v=>v[1])))/2];}
const levels=['未记录','未去过','路过','短暂停留','多次游览','深度探索'];
export default function AtlasMap({features,pref,depth,recorded,onSelect,visits=[],onVisit,...puzzleProps}:Props){const [zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[dragging,setDragging]=useState(false);const svg=useRef<SVGSVGElement>(null);const drag=useRef<{x:number,y:number,panX:number,panY:number,moved:boolean}|null>(null);const selected=features.find(f=>f.properties.name===pref);const point=selected&&pref!=='沖縄県'?center(selected):null;const reset=()=>{setZoom(1);setPan({x:0,y:0});};
useEffect(()=>{const node=svg.current;if(!node)return;const wheel=(e:WheelEvent)=>{e.preventDefault();const z=Math.max(1,Math.min(puzzleProps.puzzle?40:4,zoom*Math.exp(-e.deltaY*.002))),point=node.createSVGPoint();point.x=e.clientX;point.y=e.clientY;const matrix=node.getScreenCTM();if(!matrix)return;const p=point.matrixTransform(matrix.inverse());setPan({x:p.x-385-(p.x-385-pan.x)*z/zoom,y:p.y-208-(p.y-208-pan.y)*z/zoom});setZoom(z)};node.addEventListener('wheel',wheel,{passive:false});return()=>node.removeEventListener('wheel',wheel)},[zoom,pan,puzzleProps.puzzle]);
function region(f:AtlasFeature,inset=false){const name=f.properties.name;return <path key={f.properties.id} className={'prefecture '+(name===pref?'selected':recorded.has(name)?'recorded':'')} d={path(f,inset)} tabIndex={0} role="button" aria-label={name+(name===pref?'，当前选中':'')} onClick={()=>{if(!drag.current?.moved)onSelect(name);}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(name);}}}><title>{name}</title></path>;}
return <div className={'atlas '+(dragging?'dragging':'')}><div className="atlas-vignette"/><div className="atlas-control"><div className="pref-selector"><label className="sr-only" htmlFor="prefecture-select">都道府县</label><SelectField leadingIcon={<MapPin size={19}/>} id="prefecture-select" value={pref} onChange={e=>onSelect(e.target.value)}>{[...features].sort((a,b)=>a.properties.id-b.properties.id).map(f=><option key={f.properties.id}>{f.properties.name}</option>)}</SelectField></div><div key={pref} className="region-title"><h2>{pref}</h2><span className={'depth-indicator '+(recorded.has(pref)?'is-recorded':'')}/><span>{depth>0?levels[depth]:recorded.has(pref)?'有到访记录':'未记录'}</span></div></div><div className="zoom-controls"><div><button aria-label="放大地图" disabled={zoom>=(puzzleProps.puzzle?40:4)} onClick={()=>setZoom(z=>Math.min(puzzleProps.puzzle?40:4,z*1.3))}><Plus/></button><button aria-label="缩小地图" disabled={zoom<=1} onClick={()=>setZoom(z=>Math.max(1,z/1.3))}><Minus/></button></div><button aria-label="重置地图" onClick={reset}><LocateFixed/><span>重置</span></button></div>
<svg ref={svg} className="japan-canvas" viewBox="130 -12 510 440" aria-label="日本都道府县地图" onPointerDown={e=>{if(e.button!==0)return;drag.current={x:e.clientX,y:e.clientY,panX:pan.x,panY:pan.y,moved:false};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const d=drag.current;if(!d)return;const rect=svg.current!.getBoundingClientRect();const dx=(e.clientX-d.x)*510/rect.width,dy=(e.clientY-d.y)*440/rect.height;if(Math.abs(dx)+Math.abs(dy)>3){d.moved=true;setDragging(true);setPan({x:d.panX+dx,y:d.panY+dy});}}} onPointerUp={e=>{const d=drag.current;if(!d)return;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);setDragging(false);if(d&&!d.moved){const hit=document.elementFromPoint(e.clientX,e.clientY);const area=hit?.closest('[data-area]')?.getAttribute('data-area');if(area){onSelect(area);const cityName=hit?.closest('[data-puzzle-region]')?.getAttribute('data-puzzle-region'),city=puzzleProps.puzzleFeatures?.find(f=>f.properties.name===cityName&&f.properties.prefecture===area);if(puzzleProps.puzzle&&city){const ps=city.geometry.coordinates.flatMap(p=>p.flat()).map(project),xs=ps.map(p=>p[0]),ys=ps.map(p=>p[1]),cx=(Math.min(...xs)+Math.max(...xs))/2,cy=(Math.min(...ys)+Math.max(...ys))/2,z=Math.min(40,Math.max(1,Math.min(510/Math.max(.1,Math.max(...xs)-Math.min(...xs)),440/Math.max(.1,Math.max(...ys)-Math.min(...ys)))*.65));setZoom(z);setPan({x:(385-cx)*z,y:(208-cy)*z})}}else if(hit?.tagName.toLowerCase()==='path'){const title=hit.querySelector('title')?.textContent;if(title)onSelect(title);}}setTimeout(()=>{drag.current=null;},0);}} onPointerCancel={()=>{drag.current=null;setDragging(false);}}>
<defs><filter id="selected-glow" x="-120%" y="-120%" width="340%" height="340%"><feGaussianBlur stdDeviation="4"/></filter></defs><g className="map-shapes" style={{transform:`translate(${pan.x}px,${pan.y}px) translate(385px,208px) scale(${zoom}) translate(-385px,-208px)`}}>{features.filter(f=>f.properties.name!=='沖縄県').map(f=>region(f))}<PuzzleLayer {...puzzleProps} scope="japan" project={project} puzzleFeatures={puzzleProps.puzzleFeatures?.filter(f=>f.properties.prefecture!=="沖縄県")} zoom={zoom} prefix="jp-photo"/>{selected&&pref!=='沖縄県'&&<path className="selection-glow" d={path(selected)} filter="url(#selected-glow)"/>}{point&&<g key={pref} className="selected-marker" transform={`translate(${point[0]},${point[1]})`} aria-hidden="true"><circle className="marker-halo" r="7"/><circle r="2.5"/><g transform="translate(10,-11)"><rect rx="3" width={pref.length*9.5+17} height="26"/><text x="8" y="17.5">{pref}</text></g></g>}{visits.filter(v=>v.prefecture!=='沖縄県').map(v=>{const [x,y]=project([v.longitude,v.latitude]);return <g key={v.id} transform={`translate(${x},${y})`} className="visit-marker" role="button" tabIndex={0} aria-label={'查看打卡：'+v.label} onPointerDown={e=>e.stopPropagation()} onClick={()=>onVisit?.(v.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onVisit?.(v.id);}}}><title>{v.label} · 已确认坐标</title><circle r="6" fill="transparent"/><circle r="2.8" fill="#bd4635" stroke="#fffdf7" strokeWidth="1"/></g>;})}</g></svg>
<span className="ocean-label sea-label">日 本 海</span><span className="ocean-label pacific-label">太 平 洋</span><div className="okinawa-inset"><svg viewBox="10 398 215 115" aria-label="沖縄県概览">{features.filter(f=>f.properties.name==='沖縄県').map(f=>region(f,true))}<PuzzleLayer {...puzzleProps} puzzleFeatures={puzzleProps.puzzleFeatures?.filter(f=>f.properties.prefecture==='沖縄県')} scope="japan" project={project} zoom={zoom} prefix="okinawa-photo"/>{visits.filter(v=>v.prefecture==='沖縄県').map(v=>{const [x,y]=project([v.longitude,v.latitude]);return <circle key={v.id} cx={x} cy={y} r="4" fill="#bd4635" role="button" tabIndex={0} aria-label={'查看打卡：'+v.label} onClick={()=>onVisit?.(v.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onVisit?.(v.id);}}}/>;})}</svg><span>沖縄県</span></div><div className="map-bottom"><div className="map-legend"><span><i className="amber-dot"/>选中</span><span><i className="teal-dot"/>已记录</span><span><i/>未记录</span></div><span className="map-hint">拖动地图 · 概览位置</span></div></div>;
}
