'use client';
import SelectField from './select-field';
import NeoNotification from './ui/notification';
import {useEffect,useRef,useState} from 'react';
import SheetHeader from './ui/sheet-header';
import PhotoImage from './ui/photo-image';
import {useRevealWindow,RevealMore} from './ui/reveal-list';
import {NeoCheckbox,NeoSegmented,NeoButton} from './ui/neo';
export type ManagedItem={id:string;label:string;detail?:string;url?:string;entry?:string|null};
export default function BatchManager({records,removedRecords,photos,removedPhotos,photoRecords,initial,onApply,onClose}:{records:ManagedItem[];removedRecords:ManagedItem[];photos:ManagedItem[];removedPhotos:ManagedItem[];photoRecords?:ManagedItem[];initial?:{kind:'records'|'photos';id?:string;entry?:string};onApply:(kind:'records'|'photos',ids:string[],removed:boolean)=>Promise<void>;onClose:()=>void}){
 const ref=useRef<HTMLDialogElement>(null),[kind,setKind]=useState<'records'|'photos'>(initial?.kind||'records'),[entryFilter,setEntryFilter]=useState(initial?.entry||'all'),[trash,setTrash]=useState(false),[selected,setSelected]=useState<string[]>(initial?.id?[initial.id]:[]),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close()},[]);
 const items=(kind==='records'?(trash?removedRecords:records):(trash?removedPhotos:photos)).filter(p=>kind==='records'||entryFilter==='all'||(entryFilter==='free'?!p.entry:p.entry===entryFilter)),ids=selected.filter(id=>items.some(item=>item.id===id));
 const window=useRevealWindow(items.length,kind+trash+entryFilter+items.length);
 function reset(){setSelected([]);setConfirm(false);setError('');setMessage('')}
 async function apply(){setBusy(true);setError('');try{await onApply(kind,ids,!trash);setSelected([]);setConfirm(false);setMessage(trash?'已恢复所选项目':'已移入回收站')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <dialog ref={ref} className="batch-manager" aria-labelledby="batch-title" onCancel={e=>{if(busy)e.preventDefault();else onClose()}}><SheetHeader className="batch-header" id="batch-title" title="管理旅行记忆" onClose={onClose} closeLabel="关闭批量管理" disabled={busy}/><div className="batch-controls"><NeoSegmented label="管理类型" value={kind} onChange={v=>{if(!busy){reset();setKind(v as typeof kind)}}} options={[{value:'records',label:'旅行记录'},{value:'photos',label:'照片'}]}/><NeoSegmented label="管理范围" value={trash?'trash':'active'} onChange={v=>{if(!busy){reset();setTrash(v==='trash')}}} options={[{value:'active',label:'当前内容'},{value:'trash',label:'回收站'}]}/><div className="batch-selection">{kind==='photos'&&<SelectField aria-label="管理照片所属记录" value={entryFilter} onChange={e=>{reset();setEntryFilter(e.target.value)}}><option value="all">所有记录</option><option value="free">未加入记录</option>{(photoRecords||[...records,...removedRecords]).map(r=><option value={r.id} key={r.id}>{r.label}</option>)}</SelectField>}<button disabled={busy||!items.length} onClick={()=>{setSelected(ids.length?[]:items.slice(0,100).map(i=>i.id));setConfirm(false)}}>{ids.length?'取消选择':items.length>100?'选择前 100 项':'全选'}</button><span>{items.length} 项 · 已选 {ids.length}</span></div></div><div className="batch-list">{items.slice(0,window.visible).map(item=><div className={'batch-row '+(selected.includes(item.id)?'selected':'')} key={item.id}><NeoCheckbox checked={selected.includes(item.id)} disabled={busy||(!selected.includes(item.id)&&ids.length>=100)} onChange={e=>{setSelected(v=>e.target.checked?[...v,item.id]:v.filter(id=>id!==item.id));setConfirm(false)}}><span className="batch-item">{item.url&&!trash&&<PhotoImage src={item.url} alt=""/>}<span><strong>{item.label}</strong>{item.detail&&<small>{item.detail}</small>}</span></span></NeoCheckbox></div>)}<RevealMore visible={window.visible} total={items.length} onMore={window.more} label="显示更多项目"/>{!items.length&&<p className="batch-empty">{trash?'回收站为空':'还没有可管理的内容'}</p>}</div><footer className="batch-footer">{(error||message)&&<NeoNotification tone={error?"error":"success"} onDismiss={()=>{setError('');setMessage('')}}>{error||message}</NeoNotification>}{confirm?<div className="batch-confirm">{!trash&&<p>{kind==='records'?'关联照片也会隐藏，可从回收站恢复。':'到访记录保留，可从回收站恢复照片。'}</p>}<span>{trash?'恢复':'移入回收站'} {ids.length} {kind==='records'?'条记录':'张照片'}？</span><div><NeoButton disabled={busy} onClick={()=>setConfirm(false)}>取消</NeoButton><NeoButton variant="primary" loading={busy} onClick={()=>void apply()}>确认{trash?'恢复':'移除'}</NeoButton></div></div>:<NeoButton variant="primary" disabled={!ids.length||busy} onClick={()=>{setMessage('');setConfirm(true)}}>{trash?'恢复所选':'移入回收站'}（{ids.length}）</NeoButton>}</footer></dialog>
}
