'use client';
import {useEffect,useRef,useState} from 'react';
import {Plus,Images,NotebookPen,Check,Unlink,MapPin,Search,X,ArrowDownWideNarrow} from 'lucide-react';
import {NeoButton,NeoInput,NeoTextarea} from './ui/neo';
import SelectField from './select-field';
import SheetHeader from './ui/sheet-header';
import PhotoImage from './ui/photo-image';
import NeoNotification from './ui/notification';
import type {LibraryPhoto} from './photo-library';
import {discoverPhotos,type PhotoSort} from '../lib/photo-discovery';
import type {JournalEntry} from '../lib/travel-data';
export type EntryTarget={id:string;title:string;date:string;note:string;type:'trip'|'text';legacy?:boolean;location?:string;kind?:string;depth?:number;eaten?:number};
export type EntryCommand={op:'save';id:string;type:'trip'|'text';title:string;date:string;note:string;photos:string[]}|{op:'attach'|'detach';id:string;photos:string[]};
export default function EntrySheet({records,photos,initialId,initialPhotos=[],initialType='trip',onApply,onClose,onPhoto,onView,onRemove,readOnly=false}:{readOnly?:boolean;records:EntryTarget[];photos:LibraryPhoto[];initialId?:string;initialPhotos?:string[];initialType?:JournalEntry['type'];onApply:(command:EntryCommand)=>Promise<void>;onClose:()=>void;onPhoto:(p:LibraryPhoto)=>void;onView?:(p:LibraryPhoto,shown:LibraryPhoto[])=>void;onRemove?:(id:string)=>void}){
 const dialog=useRef<HTMLDialogElement>(null),freshId=useRef<string>('');if(!freshId.current)freshId.current=crypto.randomUUID();
 const [target,setTarget]=useState(initialId||''),[type,setType]=useState(initialType),[title,setTitle]=useState(''),[date,setDate]=useState(''),[note,setNote]=useState(''),[adding,setAdding]=useState(!initialId),[selected,setSelected]=useState(new Set(initialPhotos)),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [managing,setManaging]=useState(false),[query,setQuery]=useState(''),[sort,setSort]=useState<PhotoSort>('added');
 const baseline=useRef({title:'',date:'',note:''}),leaveAction=useRef<(()=>void)|null>(null),[discardPrompt,setDiscardPrompt]=useState(false);
 function requestLeave(action:()=>void){if(busy)return;if(!readOnly&&(title!==baseline.current.title||date!==baseline.current.date||note!==baseline.current.note)){leaveAction.current=action;setDiscardPrompt(true);dialog.current?.querySelector('.entry-sheet-scroll')?.scrollTo({top:0})}else action()}
 function requestClose(){requestLeave(onClose)}
 const selectionMode=adding||managing||!target;
 const record=records.find(r=>r.id===target),editable=!record?.legacy;
 useEffect(()=>{const d=dialog.current;d?.showModal();return()=>d?.close()},[]);
 useEffect(()=>{baseline.current={title:record?.title||'',date:record?.date||'',note:record?.note||''};if(record){setTitle(record.title);setDate(record.date);setNote(record.note);setType(record.type)}},[target]);
 const available=photos.filter(p=>!p.uploading&&!p.error&&(p.progress===undefined||p.progress===100)&&(!p.entry||p.entry===target)),members=photos.filter(p=>p.entry===target&&target),pool=adding?available.filter(p=>!target||p.entry!==target):members,shown=discoverPhotos(pool,{query,sort});
 async function apply(command:EntryCommand,close=false){setBusy(true);setError('');try{await onApply(command);if(command.op==='save')baseline.current={title:command.title,date:command.date,note:command.note};setDiscardPrompt(false);setSelected(new Set());if(close){if(command.op!=='save'&&(title!==baseline.current.title||date!==baseline.current.date||note!==baseline.current.note)){leaveAction.current=onClose;setDiscardPrompt(true)}else onClose()}else{setAdding(false);setManaging(false)}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function switchTarget(id:string){setTarget(id);setError('');if(!id){setType(initialType);setTitle('');setDate('');setNote('')}setAdding(true);setManaging(false);setQuery('')}
 const selectedShown=[...selected].filter(id=>pool.some(p=>p.id===id));
 const allVisible=shown.length>0&&shown.every(p=>selected.has(p.id));
 function selectVisible(){setSelected(old=>{const next=new Set(old);for(const p of shown){if(allVisible)next.delete(p.id);else if(next.size<100)next.add(p.id)}return next})}
 return <dialog ref={dialog} className="entry-sheet" aria-labelledby="entry-sheet-title" onCancel={e=>{if(busy)e.preventDefault();else {e.preventDefault();requestClose()}}}><SheetHeader id="entry-sheet-title" title={record?record.title:initialPhotos.length?'加入旅行记录':type==='text'?'写一段记忆':'新的旅行记录'} closeLabel="关闭旅行记录" disabled={busy} onClose={requestClose}/><div className="entry-sheet-scroll">
 {discardPrompt&&<NeoNotification tone="warning" action={{label:'放弃修改',onClick:()=>leaveAction.current?.()}} onDismiss={()=>setDiscardPrompt(false)}>文字修改尚未保存</NeoNotification>}{record&&<div className="entry-reading">{record.date&&<time>{record.date}</time>}{record.note&&<p>{record.note}</p>}</div>}{error&&<NeoNotification tone="error">{error}</NeoNotification>}
 {!initialId&&initialType!=='text'&&<label>加入<SelectField aria-label="加入旅行记录" value={target} onChange={e=>{const id=e.target.value;requestLeave(()=>switchTarget(id))}}><option value="">新建旅行记录</option>{records.filter(r=>r.type==='trip').map(r=><option key={r.id} value={r.id}>{r.title}{r.date?' · '+r.date:''}</option>)}</SelectField></label>}
 {editable&&!readOnly&&<details className="entry-fields" open={!target}><summary><NotebookPen size={16}/>{target?'编辑标题与笔记':'记录信息'}</summary><div className="entry-form-grid"><label>标题<NeoInput aria-label="记录标题" value={title} maxLength={150} onChange={e=>setTitle(e.target.value)} placeholder={type==='text'?'给这段记忆起个名字':'例如 九州夏日旅行'}/></label><label>日期<NeoInput aria-label="记录日期" type="date" value={date} onInput={e=>setDate(e.currentTarget.value)} onChange={e=>setDate(e.target.value)}/></label><label className="entry-note-field">笔记<NeoTextarea aria-label="记录笔记" value={note} maxLength={1000} rows={4} onChange={e=>setNote(e.target.value)} placeholder="把想留下的事情写在这里"/></label></div>{target&&!readOnly&&<NeoButton disabled={busy||!title.trim()||type==='text'&&!note.trim()} onClick={()=>void apply({op:'save',id:target,type,title,date,note,photos:[]})}><Check size={16}/>保存文字</NeoButton>}</details>}
 {type==='trip'&&<><div className="entry-album-toolbar"><span><Images size={17}/>{target?members.length+' 张照片':'照片'}</span>{target&&!readOnly&&<><NeoButton aria-pressed={managing} disabled={busy} onClick={()=>{setAdding(false);setManaging(v=>!v);setSelected(new Set());setQuery('');setError('')}}>{managing?'完成选择':'管理照片'}</NeoButton><NeoButton aria-pressed={adding} disabled={busy} onClick={()=>{setAdding(v=>!v);setManaging(false);setSelected(new Set());setQuery('');setError('')}}>{adding?'返回相册':<><Plus size={16}/>添加照片</>}</NeoButton></>}</div>
 <div className="photo-discovery entry-photo-discovery"><div className="photo-search"><Search size={17} aria-hidden="true"/><NeoInput type="search" aria-label="搜索记录照片" placeholder="地点、日期或笔记" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<NeoButton className="icon-button" aria-label="清除选图搜索" onClick={()=>setQuery('')}><X size={16}/></NeoButton>}</div><span className="photo-sort"><SelectField matchTriggerWidth={false} leadingIcon={<ArrowDownWideNarrow size={17}/>} aria-label="记录照片排序" value={sort} onChange={e=>setSort(e.target.value as PhotoSort)}><option value="added">最近添加</option><option value="date-desc">拍摄日期 · 从新到旧</option><option value="date-asc">拍摄日期 · 从旧到新</option></SelectField></span></div><div className="entry-photo-grid">{shown.map(p=><div className="entry-photo" key={p.id}><button aria-label={(readOnly||!selectionMode?'查看照片':selected.has(p.id)?'取消选择':'选择照片')+'：'+(p.details.place||p.details.city||p.id)} aria-pressed={readOnly||!selectionMode?undefined:selected.has(p.id)} disabled={busy||!readOnly&&selectionMode&&!selected.has(p.id)&&selectedShown.length>=100} onClick={()=>readOnly||!selectionMode?(onView?onView(p,shown):requestLeave(()=>onPhoto(p))):setSelected(old=>{const next=new Set(old);next.has(p.id)?next.delete(p.id):next.add(p.id);return next})}><PhotoImage src={p.url} alt={p.details.place||'旅行照片'}/>{!readOnly&&selectionMode&&<span className="entry-photo-check"><Check size={15}/></span>}</button><small><MapPin size={11}/>{p.details.city||p.details.prefecture||'地点待补充'}</small><small>{p.details.date||p.proposal?.date||'日期待补充'}{!p.details.date&&p.proposal?.date?' · 待确认':''}</small><button className="entry-photo-edit" disabled={busy} onClick={()=>requestLeave(()=>onPhoto(p))}>{readOnly?'查看照片':'查看与补充'}</button></div>)}</div>
 {!shown.length&&<p className="entry-sheet-empty">{query?'没有匹配的照片':adding?'暂无未归属的照片':'还没有加入照片'}{query&&<NeoButton onClick={()=>setQuery('')}>清除搜索</NeoButton>}</p>}
 {!readOnly&&selectionMode&&pool.length>0&&<div className="entry-selection-summary"><NeoButton variant="quiet" disabled={busy} onClick={selectVisible}>{allVisible?'取消本页选择':'选择当前照片'}</NeoButton><span role="status">已选 {selectedShown.length} 张</span></div>}
 </>}
 {!readOnly&&target&&onRemove&&<details className="entry-fields"><summary>管理记录</summary><NeoButton variant="quiet" disabled={busy} onClick={()=>requestLeave(()=>onRemove(target))}>移入回收站</NeoButton></details>}
 </div>{!readOnly&&<footer className="entry-sheet-footer">{!target?<NeoButton variant="primary" disabled={busy||!title.trim()||type==='text'&&!note.trim()} onClick={()=>void apply({op:'save',id:freshId.current,type,title,date,note,photos:type==='text'?[]:selectedShown},true)}><Check size={16}/>{busy?'正在保存…':'保存记录'}</NeoButton>:type==='trip'&&selectionMode?<NeoButton variant={adding?'primary':'neutral'} disabled={busy||!selectedShown.length} onClick={()=>void apply({op:adding?'attach':'detach',id:target,photos:selectedShown},!initialId&&initialPhotos.length>0)}>{adding?<Plus size={16}/>:<Unlink size={16}/>} {busy?'正在保存…':adding?'加入记录':'从记录移除'}{selectedShown.length?' · '+selectedShown.length+' 张':''}</NeoButton>:<NeoButton disabled={busy} onClick={requestClose}>完成</NeoButton>}</footer>}</dialog>;
}
