'use client';
import {useEffect,useRef,useState} from 'react';
import {Plus,Images,NotebookPen,Check,Unlink,MapPin} from 'lucide-react';
import {NeoButton,NeoInput,NeoTextarea} from './ui/neo';
import SelectField from './select-field';
import SheetHeader from './ui/sheet-header';
import PhotoImage from './ui/photo-image';
import NeoNotification from './ui/notification';
import type {LibraryPhoto} from './photo-library';
import type {JournalEntry} from '../lib/travel-data';
export type EntryTarget={id:string;title:string;date:string;note:string;type:'trip'|'text';legacy?:boolean;location?:string;kind?:string;depth?:number;eaten?:number};
export type EntryCommand={op:'save';id:string;type:'trip'|'text';title:string;date:string;note:string;photos:string[]}|{op:'attach'|'detach';id:string;photos:string[]};
export default function EntrySheet({records,photos,initialId,initialPhotos=[],initialType='trip',onApply,onClose,onPhoto,onRemove,readOnly=false}:{readOnly?:boolean;records:EntryTarget[];photos:LibraryPhoto[];initialId?:string;initialPhotos?:string[];initialType?:JournalEntry['type'];onApply:(command:EntryCommand)=>Promise<void>;onClose:()=>void;onPhoto:(p:LibraryPhoto)=>void;onRemove?:(id:string)=>void}){
 const dialog=useRef<HTMLDialogElement>(null),freshId=useRef<string>('');if(!freshId.current)freshId.current=crypto.randomUUID();
 const [target,setTarget]=useState(initialId||''),[type,setType]=useState(initialType),[title,setTitle]=useState(''),[date,setDate]=useState(''),[note,setNote]=useState(''),[adding,setAdding]=useState(!initialId),[selected,setSelected]=useState(new Set(initialPhotos)),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const record=records.find(r=>r.id===target),editable=!record?.legacy;
 useEffect(()=>{const d=dialog.current;d?.showModal();return()=>d?.close()},[]);
 useEffect(()=>{if(record){setTitle(record.title);setDate(record.date);setNote(record.note);setType(record.type)}},[target]);
 const available=photos.filter(p=>!p.uploading&&!p.error&&(p.progress===undefined||p.progress===100)&&(!p.entry||p.entry===target)),members=photos.filter(p=>p.entry===target&&target),shown=adding?available.filter(p=>!target||p.entry!==target):members;
 async function apply(command:EntryCommand,close=false){setBusy(true);setError('');try{await onApply(command);setSelected(new Set());if(close)onClose();else setAdding(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function switchTarget(id:string){setTarget(id);setError('');if(!id){setType(initialType);setTitle('');setDate('');setNote('')}setAdding(true)}
 const selectedShown=[...selected].filter(id=>shown.some(p=>p.id===id));
 return <dialog ref={dialog} className="entry-sheet" aria-labelledby="entry-sheet-title" onCancel={e=>{if(busy)e.preventDefault();else onClose()}}><SheetHeader id="entry-sheet-title" title={record?record.title:initialPhotos.length?'加入旅行记录':type==='text'?'写一段记忆':'新的旅行记录'} closeLabel="关闭旅行记录" disabled={busy} onClose={onClose}/><div className="entry-sheet-scroll">
 {record&&<div className="entry-reading">{record.date&&<time>{record.date}</time>}{record.note&&<p>{record.note}</p>}</div>}{error&&<NeoNotification tone="error">{error}</NeoNotification>}
 {!initialId&&initialType!=='text'&&<label>加入<SelectField aria-label="加入旅行记录" value={target} onChange={e=>switchTarget(e.target.value)}><option value="">新建旅行记录</option>{records.filter(r=>r.type==='trip').map(r=><option key={r.id} value={r.id}>{r.title}{r.date?' · '+r.date:''}</option>)}</SelectField></label>}
 {editable&&!readOnly&&<details className="entry-fields" open={!target}><summary><NotebookPen size={16}/>{target?'编辑标题与笔记':'记录信息'}</summary><div className="entry-form-grid"><label>标题<NeoInput aria-label="记录标题" value={title} maxLength={150} onChange={e=>setTitle(e.target.value)} placeholder={type==='text'?'给这段记忆起个名字':'例如 九州夏日旅行'}/></label><label>日期<NeoInput aria-label="记录日期" type="date" value={date} onInput={e=>setDate(e.currentTarget.value)} onChange={e=>setDate(e.target.value)}/></label><label className="entry-note-field">笔记<NeoTextarea aria-label="记录笔记" value={note} maxLength={1000} rows={4} onChange={e=>setNote(e.target.value)} placeholder="把想留下的事情写在这里"/></label></div>{target&&!readOnly&&<NeoButton disabled={busy||!title.trim()||type==='text'&&!note.trim()} onClick={()=>void apply({op:'save',id:target,type,title,date,note,photos:[]})}><Check size={16}/>保存文字</NeoButton>}</details>}
 {type==='trip'&&<><div className="entry-album-toolbar"><span><Images size={17}/>{target?members.length+' 张照片':'照片'}</span>{target&&!readOnly&&<NeoButton aria-pressed={adding} disabled={busy} onClick={()=>{setAdding(v=>!v);setSelected(new Set());setError('')}}>{adding?'返回相册':<><Plus size={16}/>添加照片</>}</NeoButton>}</div>
 <div className="entry-photo-grid">{shown.map(p=><div className="entry-photo" key={p.id}><button aria-label={(readOnly?'查看照片':selected.has(p.id)?'取消选择':'选择照片')+'：'+(p.details.place||p.details.city||p.id)} aria-pressed={readOnly?undefined:selected.has(p.id)} disabled={busy||!readOnly&&!selected.has(p.id)&&selectedShown.length>=100} onClick={()=>readOnly?onPhoto(p):setSelected(old=>{const next=new Set(old);next.has(p.id)?next.delete(p.id):next.add(p.id);return next})}><PhotoImage src={p.url} alt={p.details.place||'旅行照片'}/>{!readOnly&&<span className="entry-photo-check"><Check size={15}/></span>}</button><small><MapPin size={11}/>{p.details.city||p.details.prefecture||'地点待补充'}</small><small>{p.details.date||'日期待补充'}</small><button className="entry-photo-edit" disabled={busy} onClick={()=>onPhoto(p)}>{readOnly?'查看照片':'查看与补充'}</button></div>)}</div>
 {!shown.length&&<p className="entry-sheet-empty">{adding?'暂无未归属的照片':'还没有加入照片'}</p>}
 {!readOnly&&shown.length>0&&<NeoButton variant="quiet" disabled={busy} onClick={()=>setSelected(selectedShown.length===Math.min(shown.length,100)?new Set():new Set(shown.slice(0,100).map(p=>p.id)))}>{selectedShown.length===Math.min(shown.length,100)?'取消全选':shown.length>100?'选择前 100 张':'全选'} · {selectedShown.length} 张</NeoButton>}
 </>}
 {!readOnly&&target&&onRemove&&<details className="entry-fields"><summary>管理记录</summary><NeoButton variant="quiet" disabled={busy} onClick={()=>onRemove(target)}>移入回收站</NeoButton></details>}
 </div>{!readOnly&&<footer className="entry-sheet-footer">{!target?<NeoButton variant="primary" disabled={busy||!title.trim()||type==='text'&&!note.trim()} onClick={()=>void apply({op:'save',id:freshId.current,type,title,date,note,photos:type==='text'?[]:selectedShown},true)}><Check size={16}/>{busy?'正在保存…':'保存记录'}</NeoButton>:type==='trip'?<NeoButton variant={adding?'primary':'neutral'} disabled={busy||!selectedShown.length} onClick={()=>void apply({op:adding?'attach':'detach',id:target,photos:selectedShown},!initialId&&initialPhotos.length>0)}>{adding?<Plus size={16}/>:<Unlink size={16}/>} {busy?'正在保存…':adding?'加入记录':'从记录移除'}{selectedShown.length?' · '+selectedShown.length+' 张':''}</NeoButton>:<NeoButton disabled={busy} onClick={onClose}>完成</NeoButton>}</footer>}</dialog>;
}
