'use client';
import {useId,useMemo,useState} from 'react';
import {ChevronDown,ChevronRight,Images,MapPin,NotebookPen,Camera,Utensils} from 'lucide-react';
import {timelineGroups,chronicleItems,type ChronicleRecord,type ChroniclePhoto,type ChronicleItem} from '../lib/timeline';
import PhotoImage from './ui/photo-image';
import {NeoButton} from './ui/neo';
function Entry({item,onMap,onDetail,onPhoto}:{item:ChronicleItem;onMap:(id:string)=>void;onDetail:(id:string)=>void;onPhoto:(id:string)=>void}){
 const [expanded,setExpanded]=useState(false),noteId=useId(),longNote=item.note.length>100||item.note.split('\n').length>3;
 const photos=item.photos,label=item.type==='trip'?(item.kind==='restaurant'?'美食记录':'旅行记录'):item.type==='photo'?'照片':'文字记忆';
 const open=()=>item.type==='photo'?onPhoto(photos[0].id):onDetail(item.id.slice(6));
 return <article className={'chronicle-entry '+(!photos.length?'chronicle-entry--text ':'')+(item.type==='photo'?'chronicle-entry--photo':item.type==='text'?'chronicle-entry--diary':'')} aria-label={item.title}>
 {photos.length>0&&<div className="chronicle-album"><button className="chronicle-cover" onClick={()=>onPhoto(photos[0].id)} aria-label={'查看照片：'+item.title}><PhotoImage src={photos[0].url} alt={item.title+' 的照片'}/>{photos.length>1&&<span className="chronicle-photo-count"><Images size={14}/>{photos.length}</span>}</button>{photos.length>1&&<div className="chronicle-thumbnails" aria-label={item.title+' 的其他照片'}>{photos.slice(1).map((p,i)=><button key={p.id} onClick={()=>onPhoto(p.id)} aria-label={`查看${item.title}的照片 ${i+2}`}><PhotoImage src={p.url} alt={`照片 ${i+2}`}/></button>)}</div>}</div>}
 <div className="chronicle-entry-body"><span className="chronicle-kind">{item.type==='trip'?(item.kind==='restaurant'?<Utensils size={14}/>:<Images size={14}/>):item.type==='photo'?<Camera size={14}/>:<NotebookPen size={14}/>} {label}{item.eaten?' · 已吃过':''}{item.depth?' · '+['未记录','未去过','路过','短暂停留','多次游览','深度探索'][item.depth]:''}{item.proposedDate?' · 拍摄日期待确认':''}</span><h4><button onClick={item.mapId?()=>onMap(item.mapId!):open}>{item.title}</button></h4>{item.location&&<p className="chronicle-location">{item.location}</p>}{item.note&&<div className="chronicle-note"><p id={noteId} className={longNote&&!expanded?'is-clamped':''}>{item.note}</p>{longNote&&<button className="chronicle-note-toggle" aria-expanded={expanded} aria-controls={noteId} onClick={()=>setExpanded(v=>!v)}>{expanded?'收起笔记':'展开笔记'}<ChevronDown size={14}/></button>}</div>}<div className="chronicle-entry-actions">{item.mapId&&<NeoButton onClick={()=>onMap(item.mapId!)}><MapPin size={15}/>查看地图</NeoButton>}<NeoButton variant="quiet" onClick={open}>{item.type==='photo'?'查看照片':'查看记录'}<ChevronRight size={14}/></NeoButton></div></div></article>
}
export default function JournalTimeline({records,photos,onMap,onDetail,onPhoto}:{records:ChronicleRecord[];photos:ChroniclePhoto[];onMap:(id:string)=>void;onDetail:(id:string)=>void;onPhoto:(id:string)=>void}){
 const groups=useMemo(()=>timelineGroups(chronicleItems(records,photos)),[records,photos]),prefix=useId();
 return <div className="journal-chronicle">{groups.length>1&&<nav className="chronicle-months" aria-label="按月浏览">{groups.map(g=><a key={g.key} href={'#'+prefix+g.key}>{g.label}<span>{g.count}</span></a>)}</nav>}{groups.map(group=><section className="chronicle-month" key={group.key} aria-labelledby={prefix+group.key}><header className="chronicle-month-heading"><h3 id={prefix+group.key} tabIndex={-1}>{group.label}</h3><span>{group.count} 条记忆</span></header><ol className="chronicle-days">{group.days.map(day=><li className="chronicle-day" key={day.date}><div className="chronicle-date">{day.date?<time dateTime={day.date} aria-label={day.date}><strong>{day.day}</strong><span>{day.weekday}</span></time>:<span>日期待补充</span>}</div><div className="chronicle-day-entries">{day.records.map(item=><Entry key={item.id} item={item} onMap={onMap} onDetail={onDetail} onPhoto={onPhoto}/>)}</div></li>)}</ol></section>)}</div>
}
