'use client';
import {useState} from 'react';
import {MapPin,CalendarDays,NotebookPen,ImagePlus,SlidersHorizontal,Plus} from 'lucide-react';
import type {PhotoDetails,PhotoProposal} from '../lib/travel-data';
export type LibraryPhoto={id:string;url:string;marked:boolean;details:PhotoDetails;proposal?:PhotoProposal;metadata?:Record<string,string|number>;progress?:number;uploading?:boolean;error?:string};
export default function PhotoLibrary({items,onEdit,onUpload,onManage,onDiscard,compact=false}:{items:LibraryPhoto[];onEdit:(photo:LibraryPhoto)=>void;onUpload?:()=>void;onManage?:()=>void;onDiscard?:(photo:LibraryPhoto)=>void;compact?:boolean}){
 const [unmarked,setUnmarked]=useState(false),[noNotes,setNoNotes]=useState(false);
 const filtered=[...items].reverse().filter(p=>(!unmarked||!p.marked)&&(!noNotes||!p.details.note.trim()));
 return <section className={'photo-library '+(compact?'compact':'')} aria-label="照片记录"><div className="photo-library-heading"><div><h2>照片记录</h2><p>{items.length} 张照片 · {items.filter(p=>!p.marked).length} 张待标记</p></div><div>{onManage&&<button className="icon-button" onClick={onManage} aria-label="批量管理照片"><SlidersHorizontal size={18}/></button>}{onUpload&&<button className="primary" onClick={onUpload}><Plus size={18}/>添加照片</button>}</div></div><div className="photo-filters" aria-label="筛选照片"><button aria-pressed={!unmarked&&!noNotes} onClick={()=>{setUnmarked(false);setNoNotes(false)}}>全部</button><button aria-pressed={unmarked} onClick={()=>setUnmarked(v=>!v)}>未标记</button><button aria-pressed={noNotes} onClick={()=>setNoNotes(v=>!v)}>无笔记</button><span>{filtered.length} 张</span></div><div className="photo-library-grid">{filtered.map(p=><div className="photo-library-item" key={p.id}><button className="photo-library-card" onClick={()=>onEdit(p)} disabled={p.uploading===true||(p.progress!==undefined&&p.progress<100&&!p.error)}><img src={p.url} alt={p.details.place||'待整理的旅行照片'}/><div className="photo-card-info"><span className={!p.marked?'missing':''}><MapPin size={12}/>{p.marked?(p.details.place||p.details.city||p.details.prefecture):p.details.place?`${p.details.place} · 待确认`:p.proposal?.gps?'定位待确认':'地点待补充'}</span><span className={!p.details.date?'missing':''}><CalendarDays size={12}/>{p.details.date||p.proposal?.date||'时间待补充'}{!p.details.date&&p.proposal?.date?' · 待确认':''}</span><span className={!p.details.note.trim()?'missing':''}><NotebookPen size={12}/>{p.details.note.trim()||'笔记待补充'}</span>{(p.error||p.uploading||(p.progress!==undefined&&p.progress<100))&&<small>{p.error?`${p.error} · 点照片重试`:p.progress===100?'正在存入照片记录…':`上传 ${p.progress}%`}</small>}</div></button>{p.error&&onDiscard&&<button className="photo-card-discard" onClick={()=>onDiscard(p)}>移除失败照片</button>}</div>)}</div>{!filtered.length&&<div className="photo-library-empty"><ImagePlus size={32}/><p>{items.length?'这些条件下没有照片':'先存下照片，地点和笔记可以慢慢补充'}</p></div>}</section>;
}
