'use client';
import {useEffect,useMemo,useRef,useState,type PointerEvent,type KeyboardEvent} from 'react';
import {Move,LocateFixed} from 'lucide-react';
import {boundMapOffset,dragMapOffset,type MapOffset} from '../lib/poster-composition';
type Frame={x:number;y:number;width:number;height:number};
type Drag={id:number;clientX:number;clientY:number;width:number;height:number;start:MapOffset;next:MapOffset};
export default function PosterPreview({svg,image,title,width,height,frame,offset,onMove,disabled=false}:{svg:string;image:string;title:string;width:number;height:number;frame:Frame;offset:MapOffset;onMove:(value:MapOffset)=>void;disabled?:boolean}){
 const container=useRef<HTMLDivElement>(null),artboard=useRef<HTMLDivElement>(null),drag=useRef<Drag|null>(null),animation=useRef<number|undefined>(undefined);
 const [size,setSize]=useState({width:0,height:0}),[dragging,setDragging]=useState(false);
 // Only app-generated, XML-escaped poster markup enters this preview. Photos are sanitized JPEG data URIs.
 const markup=useMemo(()=>({__html:svg}),[svg]);
 useEffect(()=>{const el=container.current;if(!el)return;const observer=new ResizeObserver(()=>{const css=getComputedStyle(el),w=el.clientWidth-parseFloat(css.paddingLeft)-parseFloat(css.paddingRight),h=el.clientHeight-parseFloat(css.paddingTop)-parseFloat(css.paddingBottom),fit=Math.max(0,Math.min(w,h*width/height));setSize({width:fit,height:fit*height/width});});observer.observe(el);return()=>observer.disconnect();},[width,height]);
 useEffect(()=>()=>{if(animation.current!==undefined)cancelAnimationFrame(animation.current);},[]);
 function paint(value:MapOffset){artboard.current?.querySelector('#poster-map-pan')?.setAttribute('transform',`translate(${value.x*frame.width},${value.y*frame.height})`);}
 function begin(e:PointerEvent<HTMLButtonElement>){if(disabled||drag.current||!e.isPrimary||e.button!==0)return;e.preventDefault();e.currentTarget.dataset.pointerFocus='true';e.currentTarget.focus({preventScroll:true});const rect=e.currentTarget.getBoundingClientRect();e.currentTarget.setPointerCapture(e.pointerId);drag.current={id:e.pointerId,clientX:e.clientX,clientY:e.clientY,width:rect.width,height:rect.height,start:offset,next:offset};setDragging(true);}
 function move(e:PointerEvent<HTMLButtonElement>){const d=drag.current;if(!d||d.id!==e.pointerId)return;d.next=dragMapOffset(d.start,e.clientX-d.clientX,e.clientY-d.clientY,d.width,d.height);if(animation.current===undefined)animation.current=requestAnimationFrame(()=>{animation.current=undefined;if(drag.current)paint(drag.current.next);});}
 function finish(e:PointerEvent<HTMLButtonElement>,cancel=false){const d=drag.current;if(!d||d.id!==e.pointerId)return;if(animation.current!==undefined){cancelAnimationFrame(animation.current);animation.current=undefined;}const next=cancel?d.start:dragMapOffset(d.start,e.clientX-d.clientX,e.clientY-d.clientY,d.width,d.height);drag.current=null;paint(next);setDragging(false);if(!cancel)onMove(next);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}
 function keyboard(e:KeyboardEvent<HTMLButtonElement>){e.currentTarget.removeAttribute('data-pointer-focus');if(disabled||drag.current)return;const step=e.shiftKey?.05:.01,delta=({ArrowLeft:{x:-step,y:0},ArrowRight:{x:step,y:0},ArrowUp:{x:0,y:-step},ArrowDown:{x:0,y:step}} as Record<string,MapOffset>)[e.key];if(e.key==='Home'){e.preventDefault();onMove({x:0,y:0});}else if(delta){e.preventDefault();onMove(boundMapOffset({x:offset.x+delta.x,y:offset.y+delta.y}));}}
 return <div ref={container} className={'poster-preview '+(dragging?'is-dragging':'')}><div ref={artboard} className="poster-artboard" style={{width:size.width,height:size.height}}><div className="poster-vector" dangerouslySetInnerHTML={markup}/><button type="button" className="poster-drag-area" aria-label="拖动地图调整构图" aria-describedby="poster-drag-hint" disabled={disabled} style={{left:frame.x/width*100+'%',top:frame.y/height*100+'%',width:frame.width/width*100+'%',height:frame.height/height*100+'%'}} onPointerDown={begin} onPointerMove={move} onPointerUp={e=>finish(e)} onPointerCancel={e=>finish(e,true)} onLostPointerCapture={e=>finish(e,true)} onKeyDown={keyboard} onBlur={e=>e.currentTarget.removeAttribute('data-pointer-focus')}/></div><img src={image||undefined} alt={title} className="print-artwork" draggable={false}/><div className="poster-preview-tools"><p id="poster-drag-hint"><Move size={14}/>{dragging?'正在调整地图位置':'拖动地图调整位置'}<span className="poster-key-hint"> · 方向键微调</span></p><button type="button" aria-label="地图居中" onClick={()=>onMove({x:0,y:0})} disabled={disabled||(!offset.x&&!offset.y)}><LocateFixed size={16}/>居中</button></div><span className="sr-only" role="status">地图位置：横向 {Math.round(offset.x*100)}%，纵向 {Math.round(offset.y*100)}%</span></div>;
}
