'use client';
import {useState,useRef} from 'react';
import {Plus,Minus,LocateFixed,MapPin} from 'lucide-react';
import SelectField from './select-field';
import {projection,featurePath,chinaMapParts,isXishaPoint,bounds,type MapFeature,type Scope,type GeographicVisit,visitArea} from '../lib/geography';
type Props={scope:Scope;features:MapFeature[];options:string[];label:string;selected:string;recorded:Set<string>;visits:GeographicVisit[];onSelect:(area:string)=>void;onVisit:(id:string)=>void};
export default function RegionMap({scope,features,options,label,selected,recorded,visits,onSelect,onVisit}:Props){
 const [zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0});const drag=useRef<{x:number;y:number;panX:number;panY:number;moved:boolean}|null>(null);
 const parts=scope==='china'?chinaMapParts(features):{main:features,islands:[]};
 const project=projection(parts.main,900,600,scope==='world'?24:68),islandProject=projection(parts.islands,134,115,12);
 const islandVisits=visits.filter(v=>v.latitude!=null&&v.longitude!=null&&isXishaPoint(v.latitude,v.longitude));
 return <div className="atlas regional-atlas"><div className="atlas-vignette"/><div className="atlas-control"><div className="pref-selector"><MapPin size={19}/><label className="sr-only" htmlFor="region-select">{label}</label><SelectField id="region-select" value={selected} onChange={e=>onSelect(e.target.value)}>{options.map(n=><option value={n} key={n}>{n||'请选择国家 / 地区'}</option>)}</SelectField></div><div className="region-title"><h2>{selected}</h2><span className={'depth-indicator '+(recorded.has(selected)?'is-recorded':'')}/><span>{recorded.has(selected)?'有到访记录':'未记录'}</span></div></div>
 <div className="zoom-controls"><div><button aria-label="放大地图" disabled={zoom>=4} onClick={()=>setZoom(z=>Math.min(4,z+.5))}><Plus/></button><button aria-label="缩小地图" disabled={zoom<=1} onClick={()=>setZoom(z=>Math.max(1,z-.5))}><Minus/></button></div><button aria-label="重置地图" onClick={()=>{setZoom(1);setPan({x:0,y:0});}}><LocateFixed/><span>重置</span></button></div>
 <svg className="japan-canvas region-canvas" viewBox="0 0 900 600" aria-label={scope==='sichuan'?'四川市州旅行地图':scope==='china'?'中国省级旅行概览':'世界旅行概览'} onPointerDown={e=>{if(e.button!==0)return;drag.current={x:e.clientX,y:e.clientY,panX:pan.x,panY:pan.y,moved:false};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const d=drag.current;if(!d)return;const rect=e.currentTarget.getBoundingClientRect();const dx=(e.clientX-d.x)*900/rect.width,dy=(e.clientY-d.y)*600/rect.height;if(Math.abs(dx)+Math.abs(dy)>4){d.moved=true;setPan({x:d.panX+dx,y:d.panY+dy});}}} onPointerUp={e=>{const d=drag.current;drag.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);if(d&&!d.moved){const hit=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-area]');if(hit)onSelect(hit.getAttribute('data-area')!);}}} onPointerCancel={()=>{drag.current=null;}}>
 <g transform={`translate(${pan.x},${pan.y}) translate(450,300) scale(${zoom}) translate(-450,-300)`}>{parts.main.map(f=>{const n=f.properties.name;return <path key={f.properties.id} data-area={n} d={featurePath(f,project)} fillRule="evenodd" className={'prefecture '+(n===selected?'selected':recorded.has(n)?'recorded':'')} role="button" tabIndex={0} aria-label={n} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(n);}}}><title>{n}</title></path>;})}{scope==='sichuan'&&features.filter(f=>zoom>=2||f.properties.name===selected||['成都市','阿坝藏族羌族自治州','甘孜藏族自治州','凉山彝族自治州'].includes(f.properties.name)).map(f=>{const [l,b,r,t]=bounds([f]),[x,y]=project([(l+r)/2,(b+t)/2]);return <text key={'label-'+f.properties.id} x={x} y={y} className={'city-map-label '+(f.properties.name===selected?'active':'')} textAnchor="middle">{f.properties.name.replace('藏族羌族自治州','州').replace('藏族自治州','州').replace('彝族自治州','州')}</text>;})}{visits.filter(v=>v.latitude!=null&&v.longitude!=null&&!(scope==='china'&&isXishaPoint(v.latitude,v.longitude))).map(v=>{const [x,y]=project([v.longitude!,v.latitude!]);return <g key={v.id} transform={`translate(${x},${y})`} role="button" tabIndex={0} aria-label={'查看打卡：'+v.place} onPointerDown={e=>e.stopPropagation()} onClick={()=>onVisit(v.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onVisit(v.id);}}}><title>{v.place} · 已确认坐标</title><circle r="10" fill="transparent"/><circle r={visitArea(v,scope,features)===selected?4:3} fill="#bd4635" stroke="#fffdf7" strokeWidth="1"/></g>;})}</g>{parts.islands.length>0&&<g className="xisha-inset" transform="translate(742,370)" role="button" tabIndex={0} aria-label="西沙群岛局部放大，查看海南省记录" onPointerDown={e=>e.stopPropagation()} onClick={()=>onSelect('海南省')} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect('海南省');}}}><rect width="146" height="172" rx="10"/><text x="12" y="23" className="inset-heading">西沙群岛</text><g transform="translate(6,30)">{parts.islands.map(f=><path key={f.properties.id} d={featurePath(f,islandProject)} className={'island-shape '+(selected==='海南省'?'active':'')}/>)}{islandVisits.map(v=>{const [x,y]=islandProject([v.longitude!,v.latitude!]);return <g key={v.id} role="button" tabIndex={0} aria-label={"查看打卡："+v.place} onClick={e=>{e.stopPropagation();onVisit(v.id);}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();onVisit(v.id);}}}><circle cx={x} cy={y} r="9" fill="transparent"/><circle cx={x} cy={y} r="3" fill="#bd4635"><title>{v.place} · 已确认坐标</title></circle></g>;})}</g><text x="12" y="159" className="inset-caption">局部放大 · 非同比例</text></g>}</svg>
 <div className="map-bottom"><div className="map-legend"><span><i className="amber-dot"/>选中 / 落点</span><span><i className="teal-dot"/>已记录</span><span><i/>未记录</span></div><span className="map-hint">{scope==='sichuan'?'点击市州 · 放大查看名称':'拖动地图 · 简化概览'}</span></div></div>;
}
