'use client';
import {useEffect,useRef,useState} from 'react';
import {X,Download,Printer,Share2} from 'lucide-react';
import SelectField from './select-field';
import {buildPoster,posterFormats,type PosterFormat} from '../lib/travel-poster';
import type {MapFeature,GeographicVisit,Scope} from '../lib/geography';
export default function TravelPoster({scope,name,features,visits,onClose}:{scope:Scope;name:string;features:MapFeature[];visits:GeographicVisit[];onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),[title,setTitle]=useState('我的'+name+'足迹'),[format,setFormat]=useState<PosterFormat>('print'),[year,setYear]=useState('all'),[precise,setPrecise]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[downloadLink,setDownloadLink]=useState<{url:string;name:string}|null>(null);
 const subset=visits.filter(v=>year==='all'||v.date.startsWith(year+'-')),svg=buildPoster({scope,features,visits:subset,title,format,precise});
 const [image,setImage]=useState('');useEffect(()=>{const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));setImage(url);return()=>URL.revokeObjectURL(url);},[svg]);
 useEffect(()=>{dialog.current?.showModal();},[]);
 useEffect(()=>{setDownloadLink(null);},[svg]);
 useEffect(()=>()=>{if(downloadLink)URL.revokeObjectURL(downloadLink.url);},[downloadLink]);
 function download(blob:Blob,extension:string){const url=URL.createObjectURL(blob),name=`travel-${scope}-${year}-${format}.${extension}`;setDownloadLink({url,name});const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();}
 async function png(){await document.fonts.ready;const img=new Image();img.src=image;await img.decode();const {width,height}=posterFormats[format];const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('设备无法生成图片，请下载 SVG');ctx.drawImage(img,0,0);return await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('无法导出图片，请重试')),'image/png'));}
 async function exportPNG(share=false){setBusy(true);setMessage('');try{const blob=await png();if(share){const file=new File([blob],`travel-${scope}.png`,{type:'image/png'});if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title});setMessage('已打开系统分享');}else{download(blob,'png');setMessage('图片已下载，可以自行发送或设为壁纸');}}else{download(blob,'png');setMessage('图片已生成；若没有收到文件，请点下方链接保存');}}catch(e){if((e as Error).name!=='AbortError')setMessage((e as Error).message);}finally{setBusy(false);}}
 return <dialog ref={dialog} className="poster-dialog" aria-labelledby="poster-title" onCancel={onClose} onClose={onClose}><div className="sheet-header"><div><h2 id="poster-title">把足迹收藏成一张地图</h2><p>{name} · 只使用已保存的到访</p></div><button className="icon-button" aria-label="关闭地图导出" onClick={onClose}><X/></button></div><div className="poster-layout"><div className="poster-preview"><img src={image||undefined} alt={title+'，'+subset.length+' 次到访'} className="print-artwork"/></div><div className="poster-settings"><label>地图标题<input value={title} maxLength={24} onChange={e=>setTitle(e.target.value)} /></label><label>时间范围<SelectField value={year} onChange={e=>setYear(e.target.value)}><option value="all">全部记忆</option>{[...new Set(visits.map(v=>v.date.slice(0,4)))].sort().reverse().map(y=><option key={y} value={y}>{y} 年</option>)}</SelectField></label><label>画幅<SelectField value={format} onChange={e=>setFormat(e.target.value as PosterFormat)}>{Object.entries(posterFormats).map(([id,f])=><option key={id} value={id}>{f.label} · {f.width} × {f.height}</option>)}</SelectField></label><label className="checkbox"><input type="checkbox" checked={precise} onChange={e=>setPrecise(e.target.checked)}/>包含精确落点</label><p className="fine">{precise?'导出图片会包含已保存的精确位置，分享前请检查。':'默认只展示地区汇总，照片、地点名称和笔记不会进入图片。'}</p>{scope==='sichuan'&&<p className="fine">四川使用省域轮廓，城市汇总写在地图下方。没有坐标的记录仍计入到访次数。</p>}{!subset.length&&<p className="fine">这段时间还没有到访记录。可先预览地图，记录后再收藏。</p>}<div className="poster-actions"><button className="primary" disabled={busy||!image} onClick={()=>void exportPNG()}><Download size={18}/>{busy?'生成中…':'下载 PNG'}</button><button disabled={busy||!image} onClick={()=>download(new Blob([svg],{type:'image/svg+xml'}),'svg')}>下载矢量 SVG</button><button disabled={busy||!image} onClick={()=>void exportPNG(true)}><Share2 size={18}/>分享图片</button><button disabled={busy||!image} onClick={()=>window.print()}><Printer size={18}/>打印 / 存为 PDF</button></div><p className="fine" role="status">{message}</p>{downloadLink&&<a className="download-fallback" href={downloadLink.url} download={downloadLink.name}>直接保存文件</a>}<p className="fine">文件在本机生成。分享图片不会改变日志的公开设置。打印时选 A4、关闭页眉页脚。</p></div></div></dialog>;
}
