export type NeoShape='flat'|'concave'|'convex'|'pressed';
export type NeoConfig={color:string;size:number;radius:number;distance:number;intensity:number;blur:number;shape:NeoShape};
export const defaultNeo:NeoConfig={color:'#f3f1eb',size:160,radius:24,distance:8,intensity:12,blur:20,shape:'flat'};
const clamp=(n:number,min:number,max:number,fallback:number)=>Number.isFinite(n)?Math.min(max,Math.max(min,n)):fallback;
export function normalizeNeo(config:Partial<NeoConfig>):NeoConfig{return {color:/^#[0-9a-f]{6}$/i.test(config.color||'')?config.color!.toLowerCase():defaultNeo.color,size:clamp(config.size!,80,240,160),radius:clamp(config.radius!,0,80,24),distance:clamp(config.distance!,1,24,8),intensity:clamp(config.intensity!,2,30,12),blur:clamp(config.blur!,2,60,20),shape:['flat','concave','convex','pressed'].includes(config.shape||'')?config.shape!:defaultNeo.shape};}
function channels(color:string){return [1,3,5].map(i=>parseInt(color.slice(i,i+2),16));}
function mix(color:string,target:number,ratio:number){return '#'+channels(color).map(v=>Math.round(v+(target-v)*ratio).toString(16).padStart(2,'0')).join('');}
export function neoInk(color:string){const rgb=channels(normalizeNeo({color}).color).map(v=>{const s=v/255;return s<=.04045?s/12.92:((s+.055)/1.055)**2.4;});const luminance=.2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2];return luminance>.179?'#000000':'#ffffff';}
export function neoStyle(input:Partial<NeoConfig>){const c=normalizeNeo(input),dark=mix(c.color,0,c.intensity/100),light=mix(c.color,255,Math.min(1,c.intensity/100*(channels(c.color).reduce((a,b)=>a+b,0)/3<100?.45:4))),inset=c.shape==='pressed'?'inset ':'',d=c.distance;return {background:c.shape==='concave'?`linear-gradient(145deg, ${dark}, ${light})`:c.shape==='convex'?`linear-gradient(145deg, ${light}, ${dark})`:c.color,color:neoInk(c.color),borderRadius:`${c.radius}px`,boxShadow:`${inset}${d}px ${d}px ${c.blur}px ${dark}, ${inset}-${d}px -${d}px ${c.blur}px ${light}`};}
export function neoCSS(input:Partial<NeoConfig>){const c=normalizeNeo(input),s=neoStyle(c);return `.neo-surface {\n  width: ${c.size}px;\n  height: ${c.size}px;\n  background: ${s.background};\n  color: ${s.color};\n  border-radius: ${s.borderRadius};\n  box-shadow: ${s.boxShadow};\n}`;}
