import {visitInExplorerNode} from './map-explorer.ts';
import {posterVisitFeature,posterPhotoAreas,posterRegionProjection,posterPuzzleRegion,type PosterRegion} from './poster-region.ts';
import {posterPalette,type PosterColors} from './poster-style.ts';
import {boundMapOffset,posterMapFrame,type MapOffset} from './poster-composition.ts';
import {prefectureAt} from './photo-metadata.ts';
import {puzzleSVG,type PuzzlePhoto,type PuzzleRegion} from './photo-puzzle.ts';
import {featurePath,projection,chinaMapParts,isXishaPoint,visitArea,type MapFeature,type GeographicVisit,type Scope} from './geography.ts';
export const posterFormats={print:{label:'A4 打印',width:2480,height:3508},desktop:{label:'桌面壁纸',width:3840,height:2160},phone:{label:'手机壁纸',width:1440,height:2560}};
export const posterStyles={paper:{label:'朱印与列岛',description:'暖纸 · 纵排 · 朱红'},night:{label:'夜航图鉴',description:'深墨 · 暖石 · 留白'},memories:{label:'山河相册',description:'照片拼图 · 底部题签'}};
export type PosterStyle=keyof typeof posterStyles;
export type PosterFormat=keyof typeof posterFormats;
export function escapeXML(s:string){return s.replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]!));}
function labelPoint(f:MapFeature){
 const rings=f.geometry.coordinates.map(p=>p[0]);let best=rings[0],area=0;
 for(const ring of rings){let a=0;for(let i=0;i<ring.length;i++){const next=ring[(i+1)%ring.length];a+=ring[i][0]*next[1]-next[0]*ring[i][1]}if(Math.abs(a)>area){area=Math.abs(a);best=ring}}
 if(!best?.length)return undefined;const xs=best.map(p=>p[0]),ys=best.map(p=>p[1]),left=Math.min(...xs),right=Math.max(...xs),bottom=Math.min(...ys),top=Math.max(...ys);
 for(const n of [1,3,5,7]){const candidates=Array.from({length:n*n},(_,i)=>[left+(right-left)*(i%n+.5)/n,bottom+(top-bottom)*(Math.floor(i/n)+.5)/n]).sort((a,b)=>(a[0]-(left+right)/2)**2+(a[1]-(top+bottom)/2)**2-((b[0]-(left+right)/2)**2+(b[1]-(top+bottom)/2)**2));for(const p of candidates)if(prefectureAt(p[1],p[0],[f]))return p}
 return undefined;
}
export function buildPoster({scope,features,visits,title,format,precise=false,puzzle=false,photos=[],puzzleFeatures,style='paper',mapScale=1,mapOffset={x:0,y:0},labels=false,subtitle='',colors={},showSummary=true,showDates=true,titleFont='serif',region}:{region?:PosterRegion;colors?:PosterColors;showSummary?:boolean;showDates?:boolean;titleFont?:'serif'|'sans';style?:PosterStyle;mapScale?:number;mapOffset?:MapOffset;labels?:boolean;subtitle?:string;scope:Scope;features:MapFeature[];visits:GeographicVisit[];title:string;format:PosterFormat;precise?:boolean;puzzle?:boolean;photos?:PuzzlePhoto[];puzzleFeatures?:PuzzleRegion[]}){
 if(region){scope=region.scope;features=region.features;visits=visits.filter(v=>visitInExplorerNode(v,region.node));}
 const memory=style==='memories',palette=posterPalette(style,colors);
 const {width:w,height:h}=posterFormats[format],landscape=w>h,phone=format==='phone',m=w*.065,frame=posterMapFrame(w,h,scope,style),scale=Math.max(.5,Math.min(1.6,Number.isFinite(mapScale)?mapScale:1)),baseW=frame.width,baseH=frame.height,mapW=baseW*scale,mapH=baseH*scale,mapX=frame.x+(baseW-mapW)/2,mapY=frame.y+(baseH-mapH)/2,parts=scope==='china'&&(!region||region.node.id==='china')?chinaMapParts(features):{main:features,islands:[]},project=posterRegionProjection(region,parts.main,mapW,mapH,20);
 const offset=boundMapOffset(mapOffset);
 const geoFrame=region?.frame;const geoClip=geoFrame?(()=>{const [x,y]=project([geoFrame[0],geoFrame[3]]),[r,b]=project([geoFrame[2],geoFrame[1]]);return `<clipPath id="poster-geography-frame"><rect x="${x}" y="${y}" width="${r-x}" height="${b-y}"/></clipPath>`})():'';
 const areas=new Set(visits.map(v=>region?String(posterVisitFeature(v,region)?.properties.id??''):visitArea(v,scope,features)).filter(Boolean)),dates=visits.map(v=>v.date).sort(),period=dates.length?dates[0]+' — '+dates[dates.length-1]:'下一段记忆，等你启程';
 const visited=(f:MapFeature)=>areas.has(region?String(f.properties.id):f.properties.name);
 const paths=parts.main.map(f=>`<path d="${featurePath(f,project)}" fill="${visited(f)?palette.visited:palette.land}" stroke="${palette.line}" stroke-width="${Math.max(1,w/1600)}" fill-rule="evenodd"/>`).join('');
 const photoLayer=puzzle?puzzleSVG({scope,features:scope==='japan'?(puzzleFeatures||[]):parts.main,visits,photos,project,prefix:'poster-photo',groups:region?posterPhotoAreas(posterPuzzleRegion({...region,features:parts.main},puzzleFeatures),visits,photos):undefined}):'';
 const regionLabels=labels&&(region||['japan','sichuan'].includes(scope))?parts.main.filter(f=>visited(f)).slice(0,12).map(f=>{const anchor=labelPoint(f);if(!anchor)return '';const [x,y]=project(anchor);return `<text x="${x}" y="${y}" text-anchor="middle" dominant-baseline="middle" font-size="${w/85}" fill="${palette.ink}" stroke="${palette.paper}" stroke-width="${w/500}" stroke-linejoin="round" paint-order="stroke">${escapeXML(f.properties.name)}</text>`}).join(''):'';
 const points=precise?visits.filter(v=>v.latitude!=null&&v.longitude!=null).map(v=>{if(parts.islands.length&&isXishaPoint(v.latitude!,v.longitude!))return '';const [x,y]=project([v.longitude!,v.latitude!]);return `<circle cx="${x.toFixed(2)}" cy="${y.toFixed(2)}" r="${Math.max(4,w/420)}" fill="#bd4635" stroke="#fffdf7" stroke-width="2"/>`;}).join(''):'';
 const insetW=mapW*.18,insetH=mapH*.32,islandProject=projection(parts.islands,insetW,insetH*.65,10);
 const islandPoints=precise?visits.filter(v=>v.latitude!=null&&v.longitude!=null&&isXishaPoint(v.latitude,v.longitude)).map(v=>{const [x,y]=islandProject([v.longitude!,v.latitude!]);return `<circle cx="${x}" cy="${y}" r="4" fill="#bd4635"/>`;}).join(''):'';
 const inset=parts.islands.length?`<g transform="translate(${mapW-insetW-6},${mapH-insetH})"><rect width="${insetW}" height="${insetH}" rx="6" fill="${palette.paper}" stroke="${palette.muted}"/><text x="12" y="${insetH*.14}" font-size="${w/100}" fill="#65705f">西沙群岛</text><g transform="translate(0,${insetH*.18})">${parts.islands.map(f=>`<path d="${featurePath(f,islandProject)}" fill="${parts.islands.some(visited)?'#879c82':'#a7b69c'}" stroke="#657968" stroke-width="1.5"/>`).join('')}${puzzle?puzzleSVG({scope,features:parts.islands,visits,photos,project:islandProject,prefix:'poster-island-photo'}):''}${islandPoints}</g><text x="12" y="${insetH*.94}" font-size="${w/150}" fill="#65705f">局部放大 · 非同比例</text></g>`:'';
 const font=w/52,unit=region?.unit||(scope==='chengdu'?'个区县':scope==='sichuan'?'个市州':scope==='world'?'个国家 / 地区':scope==='japan'?'个都道府县':'个省级地区');
 // Summaries contain no place names, notes, photos or record identifiers.
 const attribution=(region?(region.attribution+(puzzle&&scope==='japan'&&!features.some(f=>!!f.properties.prefecture)?' · 城市：MLIT 2021 / SmartNews':'')):(scope==='chengdu'?'geoBoundaries / © OSM · 2017 · openstreetmap.org/copyright':scope==='japan'?(puzzle?'地图：GSI / dataofjapan · 城市：MLIT 2021 / SmartNews · 简化概览':'地图：GSI / dataofjapan · 简化概览'):scope==='world'?'地图：Natural Earth · 简化概览':'地图：geoBoundaries'+(scope==='china'?' / Natural Earth':' / HDX · CC BY 3.0 IGO · 简化修改')+' · 简化概览'))+(visits.some(v=>v.place_source==='geoapify')?' · 地点：Geoapify / © OSM · openstreetmap.org/copyright':'');
 const kicker=region?.kicker||(scope==='japan'?'JAPAN':scope==='sichuan'?'SICHUAN':scope==='china'?'CHINA':scope==='chengdu'?'CHENGDU':'WORLD');
 const safeTitle=title.slice(0,24),vertical=!landscape&&!phone&&!memory;
 const titleFamily=titleFont==='sans'?'PingFang SC,Microsoft YaHei,Noto Sans CJK SC,sans-serif':'Songti SC,SimSun,Noto Serif CJK SC,serif';
 const headingY=landscape?h*.33:memory?h*.84:phone?h*.205:h*.16;
 const titleRows=landscape||vertical?Array.from({length:Math.max(1,Math.ceil(safeTitle.length/8))},(_,i)=>safeTitle.slice(i*8,i*8+8)):[safeTitle];
 const displayFont=vertical?Math.min(w*.135,h*.46/Math.max(2,...titleRows.map(r=>r.length)),w*.14/titleRows.length):landscape?Math.min(w*.092,w*.29/Math.max(2,...titleRows.map(r=>r.length))):Math.min(w*.125,w*.87/Math.max(2,safeTitle.length));
 const titleX=vertical?w*.10:m;
 const titleCopy=vertical?titleRows.map((r,i)=>`<text x="${titleX+(titleRows.length-i-1)*displayFont*1.15}" y="${h*.105}" writing-mode="vertical-rl" text-orientation="upright" font-family="${titleFamily}" font-size="${displayFont}" font-weight="500" letter-spacing="${displayFont*.09}">${escapeXML(r)}</text>`).join(''):titleRows.map((r,i)=>`<text x="${m}" y="${headingY+i*displayFont*1.25}" font-family="${titleFamily}" font-size="${displayFont}" font-weight="500">${escapeXML(r)}</text>`).join('');
 const kickerY=memory&&!landscape&&safeTitle.length<=8?headingY:vertical?h*.12+displayFont*(Math.max(...titleRows.map(r=>r.length))+.8):headingY+displayFont*(landscape?(titleRows.length-1)*1.25+.5:.5);
 const copyWidth=landscape?16:35,copyText=subtitle.slice(0,35),copyRows=Array.from({length:Math.ceil(copyText.length/copyWidth)},(_,i)=>copyText.slice(i*copyWidth,(i+1)*copyWidth));
 const copyY=landscape?h*.64:memory?h*.903:phone?h*.94:h*.93;
 const summary=`${visits.length} 次到访 · ${areas.size} ${unit}`;
 const periodY=landscape?h*.84:h*.966;
 return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" role="img" aria-label="${escapeXML(title)}"><metadata>Style: ${style}. Map scale: ${scale}; offset: ${offset.x},${offset.y}. Geographic boundaries are simplified overview data. ${escapeXML(attribution)}${region?' . '+escapeXML(region.license):scope==='chengdu'?' . ODbL 1.0 https://opendatacommons.org/licenses/odbl/1-0/ . Represented year 2017. Modified: selected Chengdu districts, translated names and rounded coordinates.':scope==='sichuan'?' . License: https://creativecommons.org/licenses/by/3.0/igo/ . Source: https://data.humdata.org/dataset/cod-ab-chn . Modified: selected, translated and rounded geometries.':''}</metadata><defs>${geoClip}<clipPath id="poster-map-frame"><rect x="${frame.x}" y="${frame.y}" width="${frame.width}" height="${frame.height}"/></clipPath></defs><rect width="100%" height="100%" fill="${palette.paper}"/><g font-family="PingFang SC,Microsoft YaHei,Noto Sans CJK SC,sans-serif" fill="${palette.ink}"><g clip-path="url(#poster-map-frame)"><g id="poster-map-pan" transform="translate(${offset.x*frame.width},${offset.y*frame.height})"><g transform="translate(${mapX},${mapY})">${geoFrame?'<g clip-path="url(#poster-geography-frame)">':''}${paths}${photoLayer}${regionLabels}${points}${inset}${geoFrame?'</g>':''}</g></g></g>${titleCopy}<text x="${memory&&!landscape&&safeTitle.length<=8?w-m:m}" text-anchor="${memory&&!landscape&&safeTitle.length<=8?'end':'start'}" y="${kickerY}" font-size="${w*.015}" fill="${palette.accent}" letter-spacing="${w*.005}">${kicker}</text>${style==='paper'&&vertical?`<rect x="${m}" y="${kickerY+w*.025}" width="${w*.018}" height="${w*.018}" fill="${palette.accent}"/>`:''}${copyRows.map((copy,i)=>`<text x="${m}" y="${copyY+i*font*.95}" font-size="${font*.78}" fill="${palette.muted}">${escapeXML(copy)}</text>`).join('')}${showSummary?`<text x="${m}" y="${landscape?h*.75:phone?h*.97:h*.955}" font-size="${font*.62}" fill="${palette.muted}">${summary}</text>`:''}${showDates?`<text x="${landscape?m:w-m}" y="${periodY}" text-anchor="${landscape?'start':'end'}" font-size="${font*.58}" fill="${palette.muted}">${escapeXML(period)}</text>`:''}<text x="${m}" y="${h*.989}" font-size="${font*.36}" fill="${palette.muted}">${escapeXML(attribution)}</text></g></svg>`;
}
