import {prefectureAt} from './photo-metadata.ts';
import {puzzleSVG,type PuzzlePhoto,type PuzzleRegion} from './photo-puzzle.ts';
import {featurePath,projection,chinaMapParts,isXishaPoint,visitArea,type MapFeature,type GeographicVisit,type Scope} from './geography.ts';
export const posterFormats={print:{label:'A4 打印',width:2480,height:3508},desktop:{label:'桌面壁纸',width:3840,height:2160},phone:{label:'手机壁纸',width:1440,height:2560}};
export const posterStyles={paper:{label:'旅行书页',description:'暖纸 · 留白 · 朱红'},night:{label:'夜色收藏',description:'墨绿 · 暖金 · 山河'},memories:{label:'照片纪念',description:'大幅拼图 · 底部题签'}};
export type PosterStyle=keyof typeof posterStyles;
export type PosterFormat=keyof typeof posterFormats;
export function escapeXML(s:string){return s.replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]!));}
function labelPoint(f:MapFeature){
 const rings=f.geometry.coordinates.map(p=>p[0]);let best=rings[0],area=0;
 for(const ring of rings){let a=0;for(let i=0;i<ring.length;i++){const next=ring[(i+1)%ring.length];a+=ring[i][0]*next[1]-next[0]*ring[i][1]}if(Math.abs(a)>area){area=Math.abs(a);best=ring}}
 if(!best?.length)return undefined;const xs=best.map(p=>p[0]),ys=best.map(p=>p[1]),left=Math.min(...xs),right=Math.max(...xs),bottom=Math.min(...ys),top=Math.max(...ys);
 for(const n of [1,3,5,7]){const candidates=Array.from({length:n*n},(_,i)=>[left+(right-left)*(i%n+.5)/n,bottom+(top-bottom)*(Math.floor(i/n)+.5)/n]).sort((a,b)=>(a[0]-(left+right)/2)**2+(a[1]-(top+bottom)/2)**2-((b[0]-(left+right)/2)**2+(b[1]-(top+bottom)/2)**2));for(const p of candidates)if(prefectureAt(p[1],p[0],[f]))return p}
 return undefined;
}
export function buildPoster({scope,features,visits,title,format,precise=false,puzzle=false,photos=[],puzzleFeatures,style='paper',mapScale=1,labels=true,subtitle='把走过的地方，收藏成一张地图'}:{style?:PosterStyle;mapScale?:number;labels?:boolean;subtitle?:string;scope:Scope;features:MapFeature[];visits:GeographicVisit[];title:string;format:PosterFormat;precise?:boolean;puzzle?:boolean;photos?:PuzzlePhoto[];puzzleFeatures?:PuzzleRegion[]}){
 const dark=style==='night',memory=style==='memories',palette=dark?{paper:'#202a25',ink:'#f3ead3',muted:'#b9bea9',accent:'#ce895b',visited:'#be784e',land:'#687a62',line:'#919980'}:{paper:'#f5f3ed',ink:'#252824',muted:'#65705f',accent:'#a54234',visited:'#879c82',land:'#dfe3d9',line:'#f8f6ef'};
 const {width:w,height:h}=posterFormats[format],landscape=w>h,m=w*.065,scale=Math.max(.8,Math.min(1.1,Number.isFinite(mapScale)?mapScale:1)),baseW=w*(landscape?.57:.87),baseH=h*(landscape?.80:memory?.73:scope==='sichuan'?.59:.65),mapW=baseW*scale,mapH=baseH*scale,mapX=(landscape?w*.39:m)+(baseW-mapW)/2,mapY=h*(landscape?.07:memory?.055:.245)+(baseH-mapH)/2,parts=scope==='china'?chinaMapParts(features):{main:features,islands:[]},project=projection(parts.main,mapW,mapH,20);
 const areas=new Set(visits.map(v=>visitArea(v,scope,features)).filter(Boolean)),dates=visits.map(v=>v.date).sort(),period=dates.length?dates[0]+' — '+dates[dates.length-1]:'下一段记忆，等你启程';
 const paths=parts.main.map(f=>`<path d="${featurePath(f,project)}" fill="${areas.has(f.properties.name)?palette.visited:palette.land}" stroke="${palette.line}" stroke-width="${dark?3:landscape?2:1.5}" fill-rule="evenodd"/>`).join('');
 const photoLayer=puzzle?puzzleSVG({scope,features:scope==='japan'?(puzzleFeatures||[]):parts.main,visits,photos,project,prefix:'poster-photo'}):'';
 const regionLabels=labels&&['japan','sichuan'].includes(scope)?parts.main.filter(f=>areas.has(f.properties.name)).slice(0,12).map(f=>{const anchor=labelPoint(f);if(!anchor)return '';const [x,y]=project(anchor);return `<text x="${x}" y="${y}" text-anchor="middle" dominant-baseline="middle" font-size="${w/85}" fill="${palette.ink}" stroke="${palette.paper}" stroke-width="${w/500}" stroke-linejoin="round" paint-order="stroke">${escapeXML(f.properties.name)}</text>`}).join(''):'';
 const points=precise?visits.filter(v=>v.latitude!=null&&v.longitude!=null).map(v=>{if(scope==='china'&&isXishaPoint(v.latitude!,v.longitude!))return '';const [x,y]=project([v.longitude!,v.latitude!]);return `<circle cx="${x.toFixed(2)}" cy="${y.toFixed(2)}" r="${Math.max(4,w/420)}" fill="#bd4635" stroke="#fffdf7" stroke-width="2"/>`;}).join(''):'';
 const insetW=mapW*.18,insetH=mapH*.32,islandProject=projection(parts.islands,insetW,insetH*.65,10);
 const islandPoints=precise?visits.filter(v=>v.latitude!=null&&v.longitude!=null&&isXishaPoint(v.latitude,v.longitude)).map(v=>{const [x,y]=islandProject([v.longitude!,v.latitude!]);return `<circle cx="${x}" cy="${y}" r="4" fill="#bd4635"/>`;}).join(''):'';
 const inset=parts.islands.length?`<g transform="translate(${mapW-insetW-6},${mapH-insetH})"><rect width="${insetW}" height="${insetH}" rx="6" fill="${palette.paper}" stroke="${palette.muted}"/><text x="12" y="${insetH*.14}" font-size="${w/100}" fill="#65705f">西沙群岛</text><g transform="translate(0,${insetH*.18})">${parts.islands.map(f=>`<path d="${featurePath(f,islandProject)}" fill="${areas.has('海南省')?'#879c82':'#a7b69c'}" stroke="#657968" stroke-width="1.5"/>`).join('')}${puzzle?puzzleSVG({scope,features:parts.islands,visits,photos,project:islandProject,prefix:'poster-island-photo'}):''}${islandPoints}</g><text x="12" y="${insetH*.94}" font-size="${w/150}" fill="#65705f">局部放大 · 非同比例</text></g>`:'';
 const areaNames=[...areas].sort(),font=w/52,unit=scope==='chengdu'?'个区县':scope==='sichuan'?'个市州':scope==='world'?'个国家 / 地区':scope==='japan'?'个都道府县':'个省级地区';
 // Summaries contain no place names, notes, photos or record identifiers.
 const rows:string[]=[];let row='';let shown=0;
 for(const area of areaNames){const next=row?row+' · '+area:area;if(next.length>62&&row){rows.push(row);row='';if(rows.length===3)break;}row=row?row+' · '+area:area;shown++;}
 if(row&&rows.length<3)rows.push(row);if(shown<areaNames.length)rows[rows.length-1]+=' …';
 const attribution=scope==='chengdu'?'geoBoundaries / © OSM · 2017 · openstreetmap.org/copyright':scope==='japan'?(puzzle?'地图：GSI / dataofjapan · 城市：MLIT 2021 / SmartNews · 简化概览':'地图：GSI / dataofjapan · 简化概览'):scope==='world'?'地图：Natural Earth · 简化概览':'地图：geoBoundaries'+(scope==='china'?' / Natural Earth':' / HDX · CC BY 3.0 IGO · 简化修改')+' · 简化概览';
 const headingY=landscape?h*.26:memory?h*.845:h*.135,titleFont=landscape?w*.29/Math.max(8,Math.min(10,title.length)):w*.86/Math.max(12,title.length),summary=`${visits.length} 次到访 · ${areas.size} ${unit}`,kicker=scope==='japan'?'JAPAN':scope==='sichuan'?'SICHUAN':scope==='china'?'CHINA':scope==='chengdu'?'CHENGDU':'WORLD';
 const titleRows=landscape?Array.from({length:Math.max(1,Math.ceil(title.slice(0,24).length/10))},(_,i)=>title.slice(i*10,i*10+10)):[title.slice(0,24)];
 const copyWidth=landscape?18:35,copyText=subtitle.slice(0,35),copyRows=Array.from({length:Math.ceil(copyText.length/copyWidth)},(_,i)=>copyText.slice(i*copyWidth,(i+1)*copyWidth)),periodY=landscape?h*.79:memory?h*.933:h*.945;
 return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" role="img" aria-label="${escapeXML(title)}"><metadata>Style: ${style}. Geographic boundaries are simplified overview data. ${escapeXML(attribution)}${scope==='chengdu'?' . ODbL 1.0 https://opendatacommons.org/licenses/odbl/1-0/ . Represented year 2017. Modified: selected Chengdu districts, translated names and rounded coordinates.':scope==='sichuan'?' . License: https://creativecommons.org/licenses/by/3.0/igo/ . Source: https://data.humdata.org/dataset/cod-ab-chn . Modified: selected, translated and rounded geometries.':''}</metadata><rect width="100%" height="100%" fill="${palette.paper}"/><g font-family="PingFang SC,Microsoft YaHei,Noto Sans CJK SC,sans-serif" fill="${palette.ink}"><text x="${m}" y="${h*(landscape?.12:.075)}" font-size="${font*.62}" fill="${palette.accent}" letter-spacing="${font*.16}">${kicker} / TRAVEL JOURNAL</text><g transform="translate(${mapX},${mapY})">${paths}${photoLayer}${regionLabels}${points}${inset}</g>${titleRows.map((row,i)=>`<text x="${m}" y="${headingY+i*titleFont*1.3}" font-family="Songti SC,SimSun,Noto Serif CJK SC,serif" font-size="${titleFont}" font-weight="500">${escapeXML(row)}</text>`).join('')}${copyRows.map((copy,i)=>`<text x="${m}" y="${headingY+titleFont*(landscape?titleRows.length*1.3:.75)+i*font*1.15}" font-size="${font*.78}" fill="${palette.muted}">${escapeXML(copy)}</text>`).join('')}${!memory?`<text x="${m}" y="${landscape?h*.62:h*.224}" font-size="${font*.7}" fill="${palette.muted}">${summary}</text>`:''}<text x="${m}" y="${periodY}" font-size="${font*.7}">${escapeXML(period)}</text>${memory?`<text x="${landscape?m:w-m}" y="${landscape?periodY+font*1.7:periodY}" text-anchor="${landscape?'start':'end'}" font-size="${font*.64}" fill="${palette.muted}">${summary}</text>`:''}<text x="${m}" y="${h*.982}" font-size="${font*.4}" fill="${palette.muted}">${escapeXML(attribution)}${precise?' · 包含精确落点':' · 地区汇总，无精确落点'}</text></g></svg>`;
}
