import type {ComponentProps,ReactNode} from 'react';
import {Check,LoaderCircle,Minus,Plus} from 'lucide-react';
const cx=(...values:(string|undefined|false)[])=>values.filter(Boolean).join(' ');
export function NeoButton({variant='neutral',loading=false,children,className,disabled,type='button',...props}:ComponentProps<'button'>&{variant?:'neutral'|'primary'|'quiet';loading?:boolean}){return <button {...props} type={type} disabled={disabled||loading} aria-busy={loading||undefined} className={cx('neo-button',`neo-button--${variant}`,className)}>{loading&&<LoaderCircle className="spinner" size={18} aria-hidden="true"/>}{children}</button>;}
export function NeoSurface({children,className,inset=false,...props}:ComponentProps<'section'>&{inset?:boolean}){return <section {...props} className={cx('neo-surface',inset&&'neo-surface--inset',className)}>{children}</section>;}
export function NeoCheckbox({children,className,...props}:Omit<ComponentProps<'input'>,'type'>&{children:ReactNode}){return <label className={cx('neo-choice',className)}><span className="neo-check"><input {...props} type="checkbox"/><Check size={14} aria-hidden="true"/></span><span>{children}</span></label>;}
export function NeoSwitch({children,className,...props}:Omit<ComponentProps<'input'>,'type'|'role'>&{children:ReactNode}){return <label className={cx('neo-choice','neo-switch-label',className)}><span className="neo-switch"><input {...props} type="checkbox" role="switch"/><span aria-hidden="true"/></span><span>{children}</span></label>;}
export function NeoRange({label,value,min,max,step=1,unit='',onChange}:{label:string;value:number;min:number;max:number;step?:number;unit?:string;onChange:(value:number)=>void}){return <label className="neo-range"><span>{label}<output>{value}{unit}</output></span><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>;}
export function NeoBadge({children,tone='neutral'}:{children:ReactNode;tone?:'neutral'|'accent'|'success'}){return <span className={`neo-badge neo-badge--${tone}`}>{children}</span>;}
export function NeoInput({className,...props}:ComponentProps<'input'>){return <input {...props} className={cx('neo-input',className)}/>;}
export function NeoTextarea({className,...props}:ComponentProps<'textarea'>){return <textarea {...props} className={cx('neo-input',className)}/>;}
export function NeoSegmented({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:{value:string;label:string;icon?:ReactNode}[]}){return <div className="neo-segment" role="group" aria-label={label} style={{'--segment-count':options.length,'--segment-index':Math.max(0,options.findIndex(option=>option.value===value))} as React.CSSProperties}><span className="segment-thumb" aria-hidden="true"/>{options.map(option=><button type="button" key={option.value} aria-pressed={value===option.value} onClick={()=>onChange(option.value)}>{option.icon}{option.label}</button>)}</div>;}
export function NeoNotice({children,tone='success',className,...props}:ComponentProps<'div'>&{tone?:'success'|'error'}){return <div {...props} className={cx('neo-notice',tone==='error'&&'neo-notice--error',className)}>{children}</div>;}
export function NeoProgress(props:ComponentProps<'progress'>){return <progress {...props} className={cx('neo-progress',props.className)}/>;}
export function NeoDialog({className,...props}:ComponentProps<'dialog'>){return <dialog {...props} className={cx('neo-demo-dialog',className)}/>;}
export function NeoRadio({children,className,...props}:Omit<ComponentProps<'input'>,'type'>&{children:ReactNode}){return <label className={cx('neo-choice',className)}><span className="neo-radio"><input {...props} type="radio"/><span aria-hidden="true"/></span><span>{children}</span></label>;}
export function NeoAccordion({title,children,...props}:ComponentProps<'details'>&{title:string}){return <details {...props} className="neo-accordion"><summary>{title}</summary><div>{children}</div></details>;}
export function NeoStepper({label,value,min=0,max=99,onChange}:{label:string;value:number;min?:number;max?:number;onChange:(value:number)=>void}){return <div className="neo-stepper" role="group" aria-label={label}><button type="button" aria-label={`${label}减一`} disabled={value<=min} onClick={()=>onChange(value-1)}><Minus size={18} aria-hidden="true"/></button><output aria-live="polite">{value}</output><button type="button" aria-label={`${label}加一`} disabled={value>=max} onClick={()=>onChange(value+1)}><Plus size={18} aria-hidden="true"/></button></div>;}
