import {currentAccess} from '../../../../lib/github-auth';
import {boundedBytes} from '../../../../lib/github-service';
import {githubMode} from '../../../../lib/self-host-config';
import {githubAPI} from '../../../../lib/github-api';
import {getChatGPTUser} from '../../../chatgpt-auth';
import {database,bucket,privateHeaders} from '../../../../lib/storage';
export async function GET(_r:Request,{params}:{params:Promise<{id:string}>}){if(githubMode())return githubAPI(_r,'photo',(await params).id);const u=await getChatGPTUser();if(!u)return new Response(null,{status:401,headers:privateHeaders});try{const {id}=await params;const row=await database().prepare('SELECT object_key,type FROM photos WHERE id=? AND owner=?').bind(id,u.userId).first<{object_key:string,type:string}>();if(!row)return new Response(null,{status:404,headers:privateHeaders});const file=await bucket().get(row.object_key);if(!file)return new Response(null,{status:404,headers:privateHeaders});return new Response(file.body,{headers:{...privateHeaders,'Content-Type':'image/jpeg','Content-Disposition':'inline'}});}catch(e){console.error(e);return new Response(null,{status:503,headers:privateHeaders});}}
export async function DELETE(req:Request,{params}:{params:Promise<{id:string}>}){if(githubMode())return githubAPI(req,'delete',(await params).id);const u=await getChatGPTUser();if(!u)return new Response(null,{status:401});if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return new Response(null,{status:403});try{const {id}=await params;const row=await database().prepare('SELECT object_key FROM photos WHERE id=? AND owner=? AND checkin IS NULL').bind(id,u.userId).first<{object_key:string}>();if(!row)return new Response(null,{status:404});await bucket().delete(row.object_key);await database().prepare('DELETE FROM photos WHERE id=? AND owner=? AND checkin IS NULL').bind(id,u.userId).run();return new Response(null,{status:204});}catch{return new Response(null,{status:503});}}

export async function PATCH(req:Request,{params}:{params:Promise<{id:string}>}){if(!githubMode()){const user=await getChatGPTUser();return Response.json({error:user?'旧 Sites 适配器暂不支持照片回收站':'请先登录'},{status:user?405:401,headers:privateHeaders});}const access=await currentAccess();if(!access)return Response.json({error:'请先登录'},{status:401,headers:privateHeaders});if(access.role!=='admin')return Response.json({error:'只读访问不能修改记录'},{status:403,headers:privateHeaders});let body:{removed?:unknown}|null=null;try{body=JSON.parse((await boundedBytes(req,20000)).toString('utf8'))}catch{return Response.json({error:'请求无效'},{status:400})}if(typeof body?.removed!=='boolean')return Response.json({error:'请求无效'},{status:400});return githubAPI(req,body.removed?'hide-photo':'restore-photo',(await params).id);}
